<cfscript>
request.responseCommitted=false;

function jsonOut(required any data,numeric status=200){cfheader(statusCode=arguments.status,statusText=arguments.status>=400?"Error":"OK");cfcontent(type="application/json; charset=utf-8",reset=true);writeOutput(serializeJson(arguments.data));request.responseCommitted=true;abort;}
function explicitRoute(required string location){var target=arguments.location;if(left(target,1)=="/"&&left(target,2)!="//"&&left(target,10)!="/index.cfm"&&left(target,8)!="/static/")target="/index.cfm"&target;return target;}
function redirectTo(required string location,numeric status=302){cfheader(statusCode=arguments.status,statusText="Found");cfheader(name="Location",value=explicitRoute(arguments.location));request.responseCommitted=true;abort;}
function htmlOut(required string html,numeric status=200){cfheader(statusCode=arguments.status,statusText=arguments.status>=400?"Error":"OK");cfcontent(type="text/html; charset=utf-8",reset=true);writeOutput(arguments.html);request.responseCommitted=true;abort;}
function bodyJson(){var raw=getHttpRequestData().content;if(isBinary(raw))raw=charsetEncode(raw,"utf-8");if(!len(trim(raw&"")))return{};var parsed="";try{parsed=deserializeJson(raw);}catch(any e){throw(type="Logicore.Validation",message="Request body is not valid JSON.");}if(!isStruct(parsed)&&!isArray(parsed))throw(type="Logicore.Validation",message="Request body must be a JSON object.");return parsed;}
function apiFail(required any e){if(arguments.e.type=="Logicore.Validation")jsonOut({ok:false,error:arguments.e.message},400);writeLog(type="error",file="ussi_nexus",text="["&(request.correlationId?:"")&"] "&(arguments.e.type?:"")&": "&(arguments.e.message?:"")&" | "&(arguments.e.detail?:""));jsonOut({ok:false,error:"The request could not be completed. Reference: "&(request.correlationId?:"")},500);}
// Best-effort audit trail; never interrupts the audited action.
function audit(required string action,string targetType="",any targetId="",struct detail={},string outcome="success"){try{application.audit.record(arguments.action,currentUser(),arguments.targetType,arguments.targetId,arguments.detail,arguments.outcome);}catch(any ignored){}}
function requirePost(){if(method!="POST")jsonOut({ok:false,error:"Method not allowed."},405);}
function routePath(){var p=trim(cgi.path_info?:"");if(!len(p)||p=="/index.cfm")p=listFirst(cgi.request_uri?:"/","?");p=reReplace(p,"^/index\.cfm","");if(!len(p))p="/";if(left(p,1)!="/")p="/"&p;return p;}
function currentUser(){if(!structKeyExists(session,"user_id"))return{};return application.auth.getUser(session.user_id);}
function requireLogin(){var u=currentUser();if(!structCount(u))redirectTo("/login?next="&urlEncodedFormat(routePath()));return u;}
function requireAccess(required string section,string subsection=""){var u=requireLogin();if(!application.auth.hasAccess(u,arguments.section,arguments.subsection))jsonOut({ok:false,error:"You don't have permission to use this section."},403);return u;}
function requireAdmin(){var u=requireLogin();if(val(u.is_superadmin?:0)!=1)redirectTo("/");return u;}
function valForm(required array keys,any fallback=""){for(var k in arguments.keys)if(structKeyExists(form,k)&&len(trim(form[k]&"")))return form[k];return arguments.fallback;}
function valUrl(required string key,any fallback=""){return structKeyExists(url,arguments.key)?url[arguments.key]:arguments.fallback;}
function saveUploadAny(required array keys,required array extensions){var field="";for(var k in arguments.keys){if(structKeyExists(form,k)&&len(form[k]&"")){field=k;break;}}if(!len(field))throw(type="Logicore.Validation",message="Missing uploaded file: "&arrayToList(arguments.keys," / "));var result=fileUpload(application.uploadPath,field,"","makeunique",false);var ext=lCase(result.clientFileExt?:listLast(result.serverFile,"."));if(!arrayFindNoCase(arguments.extensions,ext)){try{fileDelete(result.serverDirectory&"/"&result.serverFile);}catch(any ignored){}throw(type="Logicore.Validation",message="Unsupported file type ."&ext&"; expected "&arrayToList(arguments.extensions,", "));}return result.serverDirectory&"/"&result.serverFile;}
function safeOutputName(any v="",string fallback="output"){var s=trim(arguments.v&"");if(!len(s))s=arguments.fallback;s=reReplace(s,"\.xlsx$","","one");return s;}
function sse(required struct payload){cfheader(name="Cache-Control",value="no-cache");cfheader(name="X-Accel-Buffering",value="no");cfcontent(type="text/event-stream; charset=utf-8",reset=true);writeOutput("data: "&serializeJson(arguments.payload)&chr(10)&chr(10));request.responseCommitted=true;abort;}
function portalAuthStruct(required struct u){var sections=[];var children=application.auth.accessibleChildren(arguments.u,"invoice-generator");if(arrayLen(children))arrayAppend(sections,"invoice-generator");for(var sec in ["sms-nonconforming","tbd2"])if(application.auth.hasAccess(arguments.u,sec))arrayAppend(sections,sec);if(len(application.auth.getRole(arguments.u,"training-tracker")))arrayAppend(sections,"training-tracker");return {username:u.username,isSuperadmin:val(u.is_superadmin?:0)==1,themePreference:lCase(u.theme_preference?:"system"),sections:sections,invoiceChildren:children,trainingRole:application.auth.getRole(u,"training-tracker")};}
function renderPortal(required struct u){var path=application.rootPath&"views/portal.html";if(!fileExists(path))return "<h1>USSI Nexus</h1><p>The generated portal shell is not present. Run the import-source-assets workflow.</p>";var html=fileRead(path,"utf-8");if(!application.auth.hasAccess(arguments.u,"invoice-generator","config")){html=reReplace(html,'(?s)<a class="side-link nav-btn[^>]*id="nav-config".*?</a>',"","one");var configStart=find('<div id="page-config"',html);var configEnd=configStart?find('</div><!-- /page-config -->',html,configStart):0;if(configStart&&configEnd)html=removeChars(html,configStart,configEnd+len('</div><!-- /page-config -->')-configStart);}html=replace(html,"__AUTH_USERNAME__",encodeForHtml(u.username),"all");html=replace(html,'data-theme="dark"','data-theme="dark" data-theme-preference="'&encodeForHtmlAttribute(lCase(u.theme_preference?:"system"))&'"',"one");var authJson=replace(serializeJson(portalAuthStruct(u)),"</","<\/","all");html=replace(html,"</head>",'<script>window.LOGICORE_AUTH='&authJson&';</script>'&chr(10)&'</head>',"one");return html;}
function workspaceShellStart(required struct u,required string activeSection,required string title,string sectionNav="",string sidebarSub=""){
    var auth=portalAuthStruct(arguments.u);var h='<!doctype html><html lang="en" data-theme="dark" data-theme-preference="'&encodeForHtmlAttribute(lCase(u.theme_preference?:"system"))&'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'&encodeForHtml(arguments.title)&' &middot; USSI Nexus</title><link rel="icon" type="image/png" href="/static/ussi_nexus_mark.png"><script src="/static/js/theme-init.js"></script><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"></head><body class="relative min-h-screen text-slate-300 font-sans"><div class="app-shell"><div id="sidebar-scrim" class="sidebar-scrim" onclick="toggleSidebar()"></div><aside class="sidebar" id="sidebar"><a class="sidebar-brand" href="/" aria-label="USSI Nexus home"><img src="/static/ussi_nexus_mark.png" alt="USSI Global"><div><div class="brand-word">USSI</div><div class="brand-sub">Nexus</div></div></a><nav class="sidebar-nav"><div class="sidebar-section-label">Portal</div>';
    if(arrayFindNoCase(auth.sections,"invoice-generator"))h&='<a class="side-link'&(arguments.activeSection=="invoice-generator"?' active':'')&'" id="portal-nav-invoice-generator" href="/?portal=invoice-generator"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="9" rx="1"/><rect x="14" y="3" width="7" height="5" rx="1"/><rect x="14" y="12" width="7" height="9" rx="1"/><rect x="3" y="16" width="7" height="5" rx="1"/></svg><span>Invoice Generator</span></a>';
    if(arrayFindNoCase(auth.sections,"sms-nonconforming"))h&='<a class="side-link'&(arguments.activeSection=="sms-nonconforming"?' active':'')&'" id="portal-nav-sms-nonconforming" href="/?portal=sms-nonconforming"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M10.3 3.3 2.3 18a1.5 1.5 0 0 0 1.3 2.2h16.8a1.5 1.5 0 0 0 1.3-2.2l-8-14.7a1.5 1.5 0 0 0-2.6 0Z"/><path d="M12 9v4M12 17h.01"/></svg><span>SMS NonConforming</span></a>';
    if(arrayFindNoCase(auth.sections,"training-tracker")){h&='<a class="side-link'&(arguments.activeSection=="training-tracker"?' active':'')&'" id="portal-nav-training-tracker" href="/training-tracker/"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 4 3 8l9 4 9-4-9-4Z"/><path d="M7 10.5V16c0 1 2.2 2.5 5 2.5s5-1.5 5-2.5v-5.5"/><path d="M21 8v6"/></svg><span>Training Tracker</span></a>';if(arguments.activeSection=="training-tracker"&&len(arguments.sidebarSub))h&=arguments.sidebarSub;}
    if(arrayFindNoCase(auth.sections,"tbd2")){h&='<a class="side-link'&(arguments.activeSection=="inventory-management"?' active':'')&'" id="portal-nav-inventory-management" href="/inventory-management/"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16v13H4zM7 4h10v3H7z"/><path d="M8 11h8M8 15h5"/></svg><span>Inventory Management</span></a>';if(arguments.activeSection=="inventory-management"&&len(arguments.sidebarSub))h&=arguments.sidebarSub;}
    if(arrayFindNoCase(auth.invoiceChildren,"config")||auth.isSuperadmin)h&='<div class="sidebar-section-label">System</div>';
    if(arrayFindNoCase(auth.invoiceChildren,"config"))h&='<a class="side-link" id="portal-nav-config" href="/?portal=invoice-generator&amp;client=config"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h9M17 6h3M4 12h3M9 12h11M4 18h13"/><circle cx="15" cy="6" r="2"/><circle cx="7" cy="12" r="2"/><circle cx="18" cy="18" r="2"/></svg><span>Config</span></a>';
    if(auth.isSuperadmin)h&='<a class="side-link'&(arguments.activeSection=="admin"?' active':'')&'" id="portal-nav-admin-permissions" href="/admin/permissions"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M19 8v6M22 11h-6"/></svg><span>User Management</span></a><a class="side-link'&(arguments.activeSection=="audit"?' active':'')&'" id="portal-nav-audit-log" href="/admin/audit"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 4h16v16H4z"/><path d="M8 9h8M8 13h8M8 17h5"/></svg><span>Audit Log</span></a><a class="side-link'&(arguments.activeSection=="api-keys"?' active':'')&'" id="portal-nav-api-keys" href="/admin/api-keys"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="8" cy="12" r="4"/><path d="M12 12h9M18 12v3M15 12v2"/></svg><span>API Keys</span></a>';
    h&='<div class="sidebar-section-label">Account</div><a class="side-link'&(arguments.activeSection=="my-account"?' active':'')&'" id="portal-nav-my-account" href="/account"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg><span>My Account</span></a>';
    h&='</nav><div class="sidebar-footer"><span class="ver-tag">USSI Nexus &middot; v9.0</span></div></aside><main class="main"><div class="topbar"><button class="sidebar-trigger" onclick="toggleSidebar()" aria-label="Open menu"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button><span class="status-dot"></span><span class="crumb-root">USSI Nexus</span><span class="crumb-sep">/</span><span class="crumb-leaf">'&encodeForHtml(arguments.title)&'</span><div class="workspace-account">';
    h&='<span>'&encodeForHtml(auth.username)&'</span><form method="post" action="/logout" class="inline"><button type="submit">Log out</button></form><div class="theme-control"><span class="toggle-label" id="toggle-label">&##9728;</span><button id="theme-toggle" onclick="toggleTheme()" title="Toggle light/dark mode" aria-label="Toggle light or dark mode"></button></div></div></div><div class="workspace-content workspace-'&encodeForHtmlAttribute(arguments.activeSection)&'">'&arguments.sectionNav&'<h1 class="workspace-title">'&encodeForHtml(arguments.title)&'</h1>';
    return h;
}
function workspaceShellEnd(){return '</div></main></div><script src="/static/js/sidebar-nav.js"></script></body></html>';}
function renderLogin(string error=""){var err=len(arguments.error)?'<div class="error">'&encodeForHtml(arguments.error)&'</div>':"";var next=encodeForHtmlAttribute(valUrl("next","/"));return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>USSI Nexus · Sign in</title><link rel="icon" type="image/png" href="/static/ussi_nexus_mark.png"><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"><style>.login-wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(420px,100%);background:##111720;border:1px solid ##27313d;border-radius:14px;padding:28px}.login-logo-wrap{display:flex;justify-content:center;padding:8px 16px;margin:0 auto 10px;background:##fff;border-radius:10px}.login-card .login-logo{display:block;max-width:210px;max-height:80px}.login-product{text-align:center;margin:0 0 24px;color:var(--text);font-family:var(--font-mono);font-size:1.05rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase}.login-card input{width:100%;margin:.35rem 0 1rem;background:##0a0d12;border:1px solid ##334155;border-radius:8px;padding:.7rem;color:##eef2f6}.login-card button{width:100%;padding:.75rem;border-radius:8px;background:var(--accent);color:##07100d;font-weight:700}.error{margin-bottom:1rem;color:##f87171}</style></head><body><div class="login-wrap"><form class="login-card" method="post" action="/login"><div class="login-logo-wrap"><img class="login-logo" src="/static/ussi_global_logo.png" alt="USSI Global"></div><div class="login-product">USSI Nexus</div><h1 style="font-size:1.35rem;margin-bottom:1rem">Sign in</h1>'&err&'<label>Username</label><input name="username" autocomplete="username" required><label>Password</label><input name="password" type="password" autocomplete="current-password" required><input type="hidden" name="next" value="'&next&'"><button type="submit">Sign in</button></form></div></body></html>';}
function renderThemedLogin(string error=""){
    var html=renderLogin(arguments.error);
    html=replace(html,'<html>','<html lang="en" data-theme="dark">','one');
    html=replace(html,'<title>USSI Nexus · Sign in</title>','<title>USSI Nexus &middot; Sign in</title><script src="/static/js/theme-init.js"></script>','one');
    html=replace(html,'background:##111720','background:var(--bg-50)','all');
    html=replace(html,'border:1px solid ##27313d','border:1px solid var(--border)','all');
    html=replace(html,'background:##0a0d12','background:var(--bg-input)','all');
    html=replace(html,'border:1px solid ##334155','border:1px solid var(--border)','all');
    html=replace(html,'color:##eef2f6','color:var(--text)','all');
    if(application.sso.enabled()){
        var ssoButton='<a class="btn" style="display:block;text-align:center;margin-top:12px" href="/auth/sso/login?next='&encodeForHtmlAttribute(valUrl("next","/"))&'">Sign in with Microsoft</a>';
        if(!application.sso.passwordLoginAllowed())html=reReplace(html,'(?s)<form method="post"[^>]*>.*?</form>',ssoButton,"one");
        else html=replace(html,'</form>','</form>'&ssoButton,'one');
    }
    return html;
}
function renderAdmin(required struct admin){var users=application.auth.listUsers();var out='<html><head><meta charset="utf-8"><title>Users & Permissions</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"><style>.wrap{max-width:1100px;margin:30px auto;padding:20px}.card{border:1px solid ##334155;border-radius:10px;padding:16px;margin:14px 0;background:##111720}input,select{background:##0a0d12;border:1px solid ##475569;border-radius:6px;padding:6px;color:##eef2f6}button{background:##2fd8a6;color:##07100d;padding:6px 10px;border-radius:6px}</style></head><body><div class="wrap"><p><a href="/">← Portal</a></p><h1 class="text-2xl">Users & Permissions</h1>'&(len(valUrl("error",""))?'<div class="card" role="alert" style="border-color:##ef4444;color:##f87171">'&encodeForHtml(valUrl("error",""))&'</div>':'')&(len(valUrl("notice",""))?'<div class="card" role="status">'&encodeForHtml(valUrl("notice",""))&'</div>':'')&'<div class="card"><h2>Create user</h2><form method="post" action="/admin/permissions/users/new"><input name="username" placeholder="Username" required> <input name="password" type="password" placeholder="Password (12+ characters)" minlength="12" required> <input name="initials" maxlength="12" placeholder="Initials"> <label><input type="checkbox" name="is_superadmin"> Superadmin</label> <button>Create</button></form></div>';
for(var u in users){var perms=application.auth.getPermissions(u.id);out&='<div class="card"><h2>'&encodeForHtml(u.username)&(val(u.is_superadmin?:0)?' · Superadmin':'')&'</h2><form method="post" action="/admin/permissions/users/'&u.id&'/set"><label><input type="checkbox" name="invoice_generator" '&(structKeyExists(perms,"invoice-generator|")?'checked':'')&'> Invoice Generator (all builders)</label><div style="margin-left:20px">';for(var child in ["promethean","amc","tcl","philips"]){out&='<label style="margin-right:12px"><input type="checkbox" name="ig_'&child&'" '&(structKeyExists(perms,"invoice-generator|"&child)?'checked':'')&'> '&encodeForHtml(child)&'</label>';}out&='</div><label><input type="checkbox" name="config_access" '&(structKeyExists(perms,"invoice-generator|config")?'checked':'')&'> Config</label> <label><input type="checkbox" name="sms_nonconforming" '&(structKeyExists(perms,"sms-nonconforming|")?'checked':'')&'> SMS NonConforming</label> <label>Training role <select name="training_role"><option value="">None</option>';for(var role in ["viewer","editor","admin"])out&='<option value="'&role&'" '&((perms["training-tracker|"]?:"")==role?'selected':'')&'>'&role&'</option>';out&='</select></label> <label><input type="checkbox" name="tbd2" '&(structKeyExists(perms,"tbd2|")?'checked':'')&'> Inventory Management</label> <button>Save permissions</button></form><form method="post" action="/admin/permissions/users/'&u.id&'/initials" style="margin-top:8px"><input name="initials" value="'&encodeForHtmlAttribute(u.initials?:"")&'" placeholder="Initials"><button>Save initials</button></form><form method="post" action="/admin/permissions/users/'&u.id&'/email" style="margin-top:8px"><input type="email" name="email" value="'&encodeForHtmlAttribute(u.email?:"")&'" placeholder="Work email (for Microsoft sign-in)"><button>Save email</button>'&(len(u.sso_subject?:"")?' <small>Linked to Microsoft account</small>':'')&'</form><form method="post" action="/admin/permissions/users/'&u.id&'/password" style="margin-top:8px"><input type="password" name="password" placeholder="New password (12+ characters)" minlength="12" required><button>Reset password</button></form>';if(u.id!=admin.id)out&='<form method="post" action="/admin/permissions/users/'&u.id&'/delete" style="margin-top:8px"><button style="background:##ef4444;color:white">Delete user</button></form>';out&='</div>';}out&='</div></body></html>';return out;}
function renderAdminWorkspace(required struct admin){
    var body=renderAdmin(arguments.admin);
    body=reReplaceNoCase(body,'^[\s\S]*?<div class="wrap">','','one');
    body=reReplaceNoCase(body,'</div></body></html>$','','one');
    body=reReplaceNoCase(body,'^<p>[\s\S]*?</p><h1[^>]*>[\s\S]*?</h1>','','one');
    body=replace(body,' · Superadmin',' &middot; Superadmin','all');
    return workspaceShellStart(arguments.admin,"admin","Users & Permissions")&body&workspaceShellEnd();
}


function renderAccount(required struct user,string error="",string notice=""){
    var auth=portalAuthStruct(arguments.user);
    var theme=lCase(arguments.user.theme_preference?:"system");
    if(!listFindNoCase("system,light,dark",theme))theme="system";
    var initials=uCase(trim(arguments.user.initials?:""));
    var h=workspaceShellStart(arguments.user,"my-account","My Account");
    h&='<div class="account-intro"><div class="account-avatar">'&encodeForHtml(len(initials)?initials:left(arguments.user.username,2))&'</div><div><span class="account-eyebrow">Personal settings</span><h2>'&encodeForHtml(arguments.user.username)&'</h2><p>Manage your profile, display preference, and account security.</p></div></div>';
    if(len(arguments.error))h&='<div class="account-alert error" role="alert">'&encodeForHtml(arguments.error)&'</div>';
    if(len(arguments.notice))h&='<div class="account-alert success" role="status">'&encodeForHtml(arguments.notice)&'</div>';
    h&='<div class="account-grid"><section class="account-panel"><div class="account-panel-head"><div><h2>Profile &amp; appearance</h2><p>Personalize how USSI Nexus identifies you and displays the portal.</p></div></div><form class="account-form" method="post" action="/account/preferences"><label><span>Username</span><input value="'&encodeForHtmlAttribute(arguments.user.username)&'" readonly aria-readonly="true"><small>Usernames are managed by an administrator.</small></label><label><span>Initials</span><input value="'&encodeForHtmlAttribute(initials)&'" readonly aria-readonly="true"><small>Initials are managed by an administrator and used in NonConforming record identifiers.</small></label><fieldset><legend>Default appearance</legend><div class="theme-options">';
    for(var option in [{value:"system",label:"System",help:"Follow this device"},{value:"light",label:"Light",help:"Always use light mode"},{value:"dark",label:"Dark",help:"Always use dark mode"}])h&='<label class="theme-option"><input type="radio" name="theme_preference" value="'&option.value&'" '&(theme==option.value?'checked':'')&'><span><strong>'&option.label&'</strong><small>'&option.help&'</small></span></label>';
    h&='</div></fieldset><button type="submit">Save preferences</button></form></section><section class="account-panel"><div class="account-panel-head"><div><h2>Password &amp; security</h2><p>Confirm your current password before choosing a new one.</p></div></div><form class="account-form" method="post" action="/account/password"><label><span>Current password</span><input type="password" name="current_password" autocomplete="current-password" required></label><label><span>New password</span><input type="password" name="new_password" autocomplete="new-password" minlength="12" required><small>Use at least 12 characters.</small></label><label><span>Confirm new password</span><input type="password" name="confirm_password" autocomplete="new-password" minlength="12" required></label><button type="submit">Update password</button></form></section></div>';
    h&='<section class="account-panel account-access"><div class="account-panel-head"><div><h2>Account access</h2><p>Your access is assigned by a portal administrator.</p></div><span class="account-role">'&(auth.isSuperadmin?'Superadmin':'Standard user')&'</span></div><div class="account-access-list">';
    if(auth.isSuperadmin)h&='<span>All portal modules</span>';else if(!arrayLen(auth.sections))h&='<span>No modules assigned</span>';else{var labels={"invoice-generator":"Invoice Generator","sms-nonconforming":"SMS NonConforming","training-tracker":"Training Tracker","tbd2":"Inventory Management"};for(var section in auth.sections)h&='<span>'&encodeForHtml(labels[section]?:section)&'</span>';}
    h&='</div></section>';
    return h&workspaceShellEnd();
}

path=routePath();method=uCase(cgi.request_method?:"GET");

// Token-authenticated integration API; never uses the browser session.
if(left(path,7)=="/api/v1"){include "routes/ApiRoutes.cfm";abort;}

// Inventory Management is a real mounted workspace (legacy permission key: tbd2).
if(left(path,len("/inventory-management"))=="/inventory-management"){include "routes/InventoryRoutes.cfm";abort;}
if(left(path,len("/training-tracker"))=="/training-tracker"){include "routes/TrainingRoutes.cfm";abort;}

// health / version
if(path=="/healthz")jsonOut({ok:true,status:"healthy",engine:"Lucee",version:"9.0-lucee"});
if(path=="/version")jsonOut({ok:true,version:"9.0-lucee",runtime:"Lucee CFML"});

// login/logout
function loginThrottleKey(){return lCase(trim(form.username?:""))&"|"&(cgi.remote_addr?:"");}
function ensureLoginThrottle(){if(!structKeyExists(application,"loginThrottle"))lock name="ussi-login-throttle" type="exclusive" timeout="5"{if(!structKeyExists(application,"loginThrottle"))application.loginThrottle={};}}
function loginThrottled(){ensureLoginThrottle();var key=loginThrottleKey();var blocked=false;lock name="ussi-login-throttle" type="readonly" timeout="5"{var entry=application.loginThrottle[key]?:{};blocked=structCount(entry)&&entry.count>=10&&dateDiff("n",entry.last,now())<15;}return blocked;}
function loginFailed(){ensureLoginThrottle();var key=loginThrottleKey();lock name="ussi-login-throttle" type="exclusive" timeout="5"{var entry=application.loginThrottle[key]?:{count:0,last:now()};if(dateDiff("n",entry.last,now())>=15)entry.count=0;entry.count++;entry.last=now();application.loginThrottle[key]=entry;if(structCount(application.loginThrottle)>5000)application.loginThrottle={};}}
function loginSucceeded(){ensureLoginThrottle();lock name="ussi-login-throttle" type="exclusive" timeout="5"{structDelete(application.loginThrottle,loginThrottleKey());}}
if(path=="/login"){
    if(method=="POST"){if(!application.sso.passwordLoginAllowed())htmlOut(renderThemedLogin("Password sign-in is disabled. Use Sign in with Microsoft."),403);if(loginThrottled()){application.audit.record("auth.login_throttled",{},"user",form.username?:"",{},"failure");htmlOut(renderThemedLogin("Too many failed sign-in attempts. Try again in 15 minutes."),429);}u=application.auth.authenticate(form.username?:"",form.password?:"");if(!structCount(u)){loginFailed();application.audit.record("auth.login_failed",{},"user",form.username?:"",{},"failure");}if(structCount(u)){loginSucceeded();sessionInvalidate();session.user_id=u.id;session.sid=replace(createUUID(),"-","","all");audit("auth.login","user",u.id,{method:"password"});dest=form.next?:url.next?:"/";if(!len(dest)||left(dest,1)!="/"||left(dest,2)=="//"||find(chr(92),dest))dest="/";redirectTo(dest);}htmlOut(renderThemedLogin("Incorrect username or password."),401);}
    if(structCount(currentUser()))redirectTo("/");htmlOut(renderThemedLogin());
}
// Microsoft Entra ID (Office 365) single sign-on. Inert unless configured.
if(path=="/auth/sso/login"){if(!application.sso.enabled())htmlOut(renderThemedLogin("Single sign-on is not configured."),404);begin=application.sso.beginLogin();session.ssoState=begin.state;session.ssoNonce=begin.nonce;session.ssoVerifier=begin.verifier;session.ssoNext=valUrl("next","/");cfheader(statusCode=302,statusText="Found");cfheader(name="Location",value=begin.url);request.responseCommitted=true;abort;}
if(path=="/auth/sso/callback"){if(!application.sso.enabled())htmlOut(renderThemedLogin("Single sign-on is not configured."),404);
    if(len(valUrl("error","")))htmlOut(renderThemedLogin("Microsoft sign-in was not completed: "&valUrl("error_description",valUrl("error",""))),400);
    if(!len(session.ssoState?:"")||compare(valUrl("state",""),session.ssoState)!=0)htmlOut(renderThemedLogin("The sign-in request could not be verified. Please try again."),400);
    ssoVerifier=session.ssoVerifier?:"";ssoNonce=session.ssoNonce?:"";ssoNext=session.ssoNext?:"/";structDelete(session,"ssoState");structDelete(session,"ssoNonce");structDelete(session,"ssoVerifier");structDelete(session,"ssoNext");
    try{identity=application.sso.completeLogin(valUrl("code",""),ssoVerifier,ssoNonce);}catch(any e){application.audit.record("auth.sso_failed",{},"sso","",{error:e.message?:""},"failure");writeLog(type="warning",file="ussi_nexus",text="["&(request.correlationId?:"")&"] sso: "&(e.message?:""));htmlOut(renderThemedLogin("Microsoft sign-in failed. Reference: "&(request.correlationId?:"")),400);}
    ssoUser=application.auth.findBySsoSubject(identity.subject);
    if(!structCount(ssoUser)&&len(identity.email)){ssoUser=application.auth.findByEmail(identity.email);if(structCount(ssoUser)){application.auth.linkSso(ssoUser.id,identity.subject,identity.email);audit("auth.sso_linked","user",ssoUser.id,{email:identity.email});}}
    if(!structCount(ssoUser)&&application.sso.autoProvision()&&len(identity.email)){newSsoId=application.auth.createSsoUser(identity.email,identity.subject,identity.name);ssoUser=application.auth.getUser(newSsoId);application.audit.record("user.sso_provisioned",{id:newSsoId,username:ssoUser.username?:""},"user",newSsoId,{email:identity.email,tenant:identity.tenant});}
    if(!structCount(ssoUser)){application.audit.record("auth.sso_unlinked",{},"sso",identity.email,{tenant:identity.tenant},"failure");htmlOut(renderThemedLogin("Your Microsoft account ("&identity.email&") is not linked to a portal user. Ask an administrator to add your email address to your account."),403);}
    sessionInvalidate();session.user_id=ssoUser.id;session.sid=replace(createUUID(),"-","","all");audit("auth.login","user",ssoUser.id,{method:"sso",tenant:identity.tenant});
    dest=ssoNext;if(!len(dest)||left(dest,1)!="/"||left(dest,2)=="//"||find(chr(92),dest))dest="/";redirectTo(dest);}
if(path=="/logout"){if(method!="POST")redirectTo("/");audit("auth.logout");sessionInvalidate();redirectTo("/login");}

// main portal
if(path=="/"){u=requireLogin();if(compareNoCase(url.client?:"","config")==0&&!application.auth.hasAccess(u,"invoice-generator","config"))jsonOut({ok:false,error:"You don't have permission to use Config."},403);htmlOut(renderPortal(u));}


// self-service account
if(path=="/account"&&method=="GET"){u=requireLogin();notice="";if((url.saved?:"")=="preferences")notice="Profile and appearance preferences saved.";else if((url.saved?:"")=="password")notice="Password updated successfully.";htmlOut(renderAccount(u,"",notice));}
if(path=="/account/preferences"&&method=="POST"){u=requireLogin();theme=lCase(trim(form.theme_preference?:"system"));if(!listFindNoCase("system,light,dark",theme))htmlOut(renderAccount(u,"Choose System, Light, or Dark appearance."),400);application.auth.updatePreferences(u.id,theme);audit("account.preferences","user",u.id,{theme_preference:theme});redirectTo("/account?saved=preferences");}
if(path=="/account/theme"&&method=="POST"){u=requireLogin();theme=lCase(trim(form.theme?:""));if(!listFindNoCase("system,light,dark",theme))jsonOut({ok:false,error:"Invalid theme preference."},400);application.auth.updatePreferences(u.id,theme);jsonOut({ok:true,theme:theme});}
if(path=="/account/password"&&method=="POST"){u=requireLogin();current=form.current_password?:"";nextPassword=form.new_password?:"";confirmation=form.confirm_password?:"";if(len(application.auth.validatePassword(nextPassword)))htmlOut(renderAccount(u,"New "&lCase(application.auth.validatePassword(nextPassword))),400);if(compare(nextPassword,confirmation)!=0)htmlOut(renderAccount(u,"New password and confirmation do not match."),400);if(!application.auth.changeOwnPassword(u.id,current,nextPassword)){audit("account.password_change","user",u.id,{},"failure");htmlOut(renderAccount(u,"Current password is incorrect."),400);}audit("account.password_change","user",u.id);redirectTo("/account?saved=password");}

// admin
if(path=="/admin/permissions"&&method=="GET"){admin=requireAdmin();htmlOut(renderAdminWorkspace(admin));}
if(path=="/admin/permissions/users/new"&&method=="POST"){requireAdmin();try{newId=application.auth.createUser(form.username?:"",form.password?:"",structKeyExists(form,"is_superadmin"),form.initials?:"");audit("user.create","user",newId,{username:trim(form.username?:""),is_superadmin:structKeyExists(form,"is_superadmin")});}catch(any e){audit("user.create","user",trim(form.username?:""),{error:e.message?:""},"failure");writeLog(type="warning",file="ussi_nexus",text="["&(request.correlationId?:"")&"] createUser failed: "&(e.message?:""));redirectTo("/admin/permissions?error="&urlEncodedFormat(e.type=="Logicore.Validation"?e.message:"The user could not be created. Reference: "&(request.correlationId?:"")));}redirectTo("/admin/permissions?notice="&urlEncodedFormat("User "&trim(form.username?:"")&" created."));}
m=reFind("^/admin/permissions/users/([0-9]+)/(delete|password|initials|set|email)$",path,1,true);
if(m.len[1]){admin=requireAdmin();uid=val(mid(path,m.pos[2],m.len[2]));action=mid(path,m.pos[3],m.len[3]);if(method!="POST")redirectTo("/admin/permissions");targetUser=application.auth.getUser(uid);if(action=="delete"&&uid!=admin.id){application.auth.deleteUser(uid);audit("user.delete","user",uid,{username:targetUser.username?:""});}else if(action=="password"){pwProblem=application.auth.validatePassword(form.password?:"");if(len(pwProblem))redirectTo("/admin/permissions?error="&urlEncodedFormat(pwProblem));application.auth.updateUser(id=uid,password=form.password);audit("user.password_reset","user",uid,{username:targetUser.username?:""});}else if(action=="email"){try{application.auth.setEmail(uid,form.email?:"");}catch(any e){redirectTo("/admin/permissions?error="&urlEncodedFormat(e.message));}audit("user.email","user",uid,{username:targetUser.username?:"",email:lCase(trim(form.email?:""))});}else if(action=="initials"){if(len(trim(form.initials?:""))>12)redirectTo("/admin/permissions?error="&urlEncodedFormat("Initials must be 12 characters or fewer."));application.auth.updateUser(id=uid,initials=form.initials?:"");audit("user.initials","user",uid,{initials:uCase(trim(form.initials?:""))});}else if(action=="set"){permSummary={};for(pk in ["invoice_generator","ig_promethean","ig_amc","ig_tcl","ig_philips","config_access","sms_nonconforming","tbd2"])permSummary[pk]=structKeyExists(form,pk);permSummary.training_role=form.training_role?:"";audit("user.permissions","user",uid,{username:targetUser.username?:"",permissions:permSummary});
    for(spec in [{s:"invoice-generator",f:"invoice_generator"},{s:"sms-nonconforming",f:"sms_nonconforming"},{s:"tbd2",f:"tbd2"}]){if(structKeyExists(form,spec.f))application.auth.setPermission(uid,spec.s);else application.auth.clearPermission(uid,spec.s);}
    for(c in ["promethean","amc","tcl","philips"]){if(structKeyExists(form,"ig_"&c))application.auth.setPermission(uid,"invoice-generator",c);else application.auth.clearPermission(uid,"invoice-generator",c);}
    if(structKeyExists(form,"config_access"))application.auth.setPermission(uid,"invoice-generator","config");else application.auth.clearPermission(uid,"invoice-generator","config");
    application.auth.clearPermission(uid,"training-tracker");if(len(form.training_role?:""))application.auth.setPermission(uid,"training-tracker","",form.training_role);
}redirectTo("/admin/permissions");}

// API keys (superadmin)
if(path=="/admin/api-keys"&&method=="GET"){admin=requireAdmin();h=workspaceShellStart(admin,"api-keys","API Keys");
    if(len(valUrl("error","")))h&='<div class="card" role="alert" style="border-color:##ef4444;color:##f87171">'&encodeForHtml(valUrl("error",""))&'</div>';
    if(structKeyExists(session,"newApiKey")){nk=session.newApiKey;structDelete(session,"newApiKey");h&='<div class="card" role="status"><h2>Key created: '&encodeForHtml(nk.name)&'</h2><p>Copy it now; it will not be shown again.</p><p><code style="user-select:all;word-break:break-all">'&encodeForHtml(nk.key)&'</code></p><p class="muted">Send it as <code>Authorization: Bearer &lt;key&gt;</code>. Scopes: '&encodeForHtml(arrayToList(nk.scopes,", "))&'</p></div>';}
    h&='<div class="card"><h2>Create key</h2><form method="post" action="/admin/api-keys/new"><input name="name" placeholder="Integration name (e.g. warehouse-sync)" required maxlength="120"> ';for(sc in application.apiKeys.availableScopes())h&='<label style="margin-right:10px"><input type="checkbox" name="scopes" value="'&encodeForHtmlAttribute(sc)&'"> '&encodeForHtml(sc)&'</label>';h&='<button type="submit">Create</button></form><p class="muted">See <code>docs/API.md</code> for endpoints. Keys are hashed at rest and can be revoked at any time.</p></div>';
    h&='<div class="card"><h2>Existing keys</h2><table><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Created</th><th>Last used</th><th>Status</th><th></th></tr></thead><tbody>';
    for(k in application.apiKeys.list()){revoked=len(k.revoked_at?:"");h&='<tr><td>'&encodeForHtml(k.name)&'</td><td><code>nxk_'&encodeForHtml(k.key_prefix)&'_…</code></td><td>'&encodeForHtml(k.scopes)&'</td><td>'&encodeForHtml(k.created_by?:"")&' &middot; '&encodeForHtml(dateTimeFormat(k.created_at,"yyyy-mm-dd HH:nn"))&'</td><td>'&(len(k.last_used_at?:"")?encodeForHtml(dateTimeFormat(k.last_used_at,"yyyy-mm-dd HH:nn")):"never")&'</td><td>'&(revoked?'revoked '&encodeForHtml(dateTimeFormat(k.revoked_at,"yyyy-mm-dd")):'active')&'</td><td>'&(revoked?'':'<form method="post" action="/admin/api-keys/'&k.id&'/revoke" onsubmit="return confirm(''Revoke this key? Integrations using it will stop working immediately.'')"><button class="danger">Revoke</button></form>')&'</td></tr>';}
    h&='</tbody></table></div>';htmlOut(h&workspaceShellEnd());}
if(path=="/admin/api-keys/new"&&method=="POST"){admin=requireAdmin();scopeList=[];if(structKeyExists(form,"scopes"))scopeList=listToArray(form.scopes);try{created=application.apiKeys.create(form.name?:"",scopeList,admin.username);}catch(any e){redirectTo("/admin/api-keys?error="&urlEncodedFormat(e.message));}session.newApiKey=created;audit("api_key.create","api_key",created.id,{name:created.name,prefix:created.prefix,scopes:created.scopes});redirectTo("/admin/api-keys");}
km=reFind("^/admin/api-keys/([0-9]+)/revoke$",path,1,true);if(km.len[1]&&method=="POST"){admin=requireAdmin();kid=val(mid(path,km.pos[2],km.len[2]));if(application.apiKeys.revoke(kid))audit("api_key.revoke","api_key",kid);redirectTo("/admin/api-keys");}

// Audit log (superadmin)
if(path=="/admin/audit"&&method=="GET"){admin=requireAdmin();filters={actor:valUrl("actor",""),action:valUrl("action",""),targetType:valUrl("target_type",""),targetId:valUrl("target_id",""),outcome:valUrl("outcome",""),startDate:valUrl("start_date",""),endDate:valUrl("end_date",""),limit:100,offset:max(val(valUrl("offset",0)),0)};res=application.audit.search(argumentCollection=filters);h=workspaceShellStart(admin,"audit","Audit Log");
    h&='<div class="card"><form method="get" action="/admin/audit" class="flex flex-wrap gap-2 items-center"><input name="actor" placeholder="Actor" value="'&encodeForHtmlAttribute(filters.actor)&'"><select name="action" aria-label="Action"><option value="">All actions</option>';for(act in application.audit.actions())h&='<option value="'&encodeForHtmlAttribute(act)&'"'&(act==filters.action?' selected':'')&'>'&encodeForHtml(act)&'</option>';
    h&='</select><input name="target_id" placeholder="Target" value="'&encodeForHtmlAttribute(filters.targetId)&'"><select name="outcome" aria-label="Outcome"><option value="">Any outcome</option><option value="success"'&(filters.outcome=="success"?' selected':'')&'>success</option><option value="failure"'&(filters.outcome=="failure"?' selected':'')&'>failure</option></select><input type="date" name="start_date" value="'&encodeForHtmlAttribute(filters.startDate)&'"><input type="date" name="end_date" value="'&encodeForHtmlAttribute(filters.endDate)&'"><button type="submit">Filter</button> <a class="btn" href="/admin/audit/export.csv?'&encodeForHtmlAttribute(cgi.query_string?:"")&'">Export CSV</a></form></div>';
    h&='<p class="muted">'&res.total&' event'&(res.total==1?'':'s')&(res.total>res.limit?' &middot; showing '&(res.offset+1)&'&ndash;'&min(res.offset+res.limit,res.total):'')&'</p><div style="overflow:auto"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Outcome</th><th>Detail</th><th>IP</th><th>Ref</th></tr></thead><tbody>';
    for(ev in res.rows){detailText=structCount(ev.detail?:{})?serializeJson(ev.detail):"";h&='<tr><td>'&encodeForHtml(dateTimeFormat(ev.occurred_at,"yyyy-mm-dd HH:nn:ss"))&'</td><td>'&encodeForHtml(ev.actor_username?:"")&(ev.actor_kind?:"user"!="user"?' <small>('&encodeForHtml(ev.actor_kind)&')</small>':'')&'</td><td><code>'&encodeForHtml(ev.action?:"")&'</code></td><td>'&encodeForHtml(ev.target_type?:"")&(len(ev.target_id?:"")?' '&encodeForHtml(ev.target_id):'')&'</td><td>'&encodeForHtml(ev.outcome?:"")&'</td><td style="max-width:420px;word-break:break-all"><small>'&encodeForHtml(left(detailText,400))&(len(detailText)>400?'&hellip;':'')&'</small></td><td>'&encodeForHtml(ev.remote_addr?:"")&'</td><td><small>'&encodeForHtml(ev.correlation_id?:"")&'</small></td></tr>';}
    if(!arrayLen(res.rows))h&='<tr><td colspan="8" class="muted">No audit events match.</td></tr>';h&='</tbody></table></div>';
    pager="";if(res.offset>0)pager&='<a class="btn" href="/admin/audit?'&encodeForHtmlAttribute(reReplace(cgi.query_string?:"","(^|&)offset=[0-9]*","","all")&"&offset="&max(res.offset-res.limit,0))&'">&larr; Newer</a> ';if(res.offset+res.limit<res.total)pager&='<a class="btn" href="/admin/audit?'&encodeForHtmlAttribute(reReplace(cgi.query_string?:"","(^|&)offset=[0-9]*","","all")&"&offset="&(res.offset+res.limit))&'">Older &rarr;</a>';if(len(pager))h&='<p>'&pager&'</p>';
    htmlOut(h&workspaceShellEnd());}
if(path=="/admin/audit/export.csv"&&method=="GET"){admin=requireAdmin();res=application.audit.search(actor=valUrl("actor",""),action=valUrl("action",""),targetType=valUrl("target_type",""),targetId=valUrl("target_id",""),outcome=valUrl("outcome",""),startDate=valUrl("start_date",""),endDate=valUrl("end_date",""),limit=1000,offset=0);audit("audit.export","audit","",{rows:arrayLen(res.rows)});cfheader(name="Content-Disposition",value='attachment; filename="audit_log_'&dateFormat(now(),"yyyymmdd")&'.csv"');cfcontent(type="text/csv; charset=utf-8",reset=true);writeOutput(application.audit.toCsv(res.rows));request.responseCommitted=true;abort;}

// Config endpoints
if(path=="/config/serial_rules"||path=="/get_serial_rules"){requireAccess("invoice-generator","config");if(method=="GET")jsonOut({ok:true,rules:application.configService.getSerialRules().rules?:[]});requirePost();try{d=bodyJson();application.configService.saveSerialRules(isStruct(d)&&structKeyExists(d,"rules")?d:{rules:d});audit("config.serial_rules","config","serial_rules",{rule_count:arrayLen(isStruct(d)&&structKeyExists(d,"rules")?d.rules:d)});jsonOut({ok:true});}catch(any e){apiFail(e);}}
if(path=="/get_storage_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getStoragePrices(),defaults:application.configService.storageDefaults()});}
if(path=="/set_storage_prices"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();if(d.reset?:false)application.configService.resetStoragePrices();else application.configService.saveStoragePrices(d.prices?:d);audit("config.storage_prices","config","storage_prices",{reset:d.reset?:false,prices:d.prices?:d});jsonOut({ok:true,prices:application.configService.getStoragePrices(),defaults:application.configService.storageDefaults()});}catch(any e){apiFail(e);}}
if(path=="/get_fedex_shipment_defaults"){requireAccess("invoice-generator","config");jsonOut({ok:true,defaults:application.configService.getFedexDefaults()});}
if(path=="/set_fedex_shipment_defaults"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();application.configService.saveFedexDefaults(d.defaults?:d);audit("config.fedex_defaults","config","fedex_shipment_defaults",{defaults:d.defaults?:d});jsonOut({ok:true,defaults:application.configService.getFedexDefaults()});}catch(any e){apiFail(e);}}
if(path=="/get_philips_dimensions"){requireAccess("invoice-generator","config");d=application.configService.getPhilipsDimensions();jsonOut({ok:true,dimensions:d,count:structCount(d)});}
if(path=="/upload_philips_dimensions"&&method=="POST"){requireAccess("invoice-generator","config");try{p=saveUploadAny(["file","dimensions"],["xlsx"]);d=application.configService.readDimensionsWorkbook(p);application.configService.savePhilipsDimensions(d);audit("config.philips_dimensions_replaced","config","philips_dimensions",{count:structCount(d)});jsonOut({ok:true,count:structCount(d)});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/download_philips_dimensions"){requireAccess("invoice-generator","config");name="Philips_Dimensions.xlsx";application.configService.writeDimensionsWorkbook(application.outputPath&name,application.configService.getPhilipsDimensions(),"Dimensions");application.outputs.register(name,"config");redirectTo("/download/"&urlEncodedFormat(name));}
if(path=="/get_philips_repair_cost"){requireAccess("invoice-generator","config");tiers=application.configService.getPhilipsRepairCost();jsonOut({ok:true,tiers:tiers,rows:tiers,repair_cost:tiers});}
if(path=="/set_philips_repair_cost"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();tiersIn=isArray(d)?d:(d.tiers?:d.rows?:d.repair_cost?:"");if(!isArray(tiersIn))throw(type="Logicore.Validation",message="Send the repair cost tiers as an array.");application.configService.savePhilipsRepairCost(tiersIn);audit("config.philips_repair_cost","config","philips_repair_cost",{tiers:tiersIn});jsonOut({ok:true,rows:application.configService.getPhilipsRepairCost(),tiers:application.configService.getPhilipsRepairCost()});}catch(any e){apiFail(e);}}
if(path=="/get_amc_dimensions"){requireAccess("invoice-generator","config");d=application.configService.getAmcDimensions();jsonOut({ok:true,dimensions:d,count:structCount(d)});}
if(path=="/upload_amc_dimensions"&&method=="POST"){requireAccess("invoice-generator","config");try{p=saveUploadAny(["file","dimensions"],["xlsx"]);d=application.configService.readDimensionsWorkbook(p);application.configService.saveAmcDimensions(d);audit("config.amc_dimensions_replaced","config","amc_dimensions",{count:structCount(d)});jsonOut({ok:true,count:structCount(d)});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/download_amc_dimensions"){requireAccess("invoice-generator","config");name="AMC_Dimensions.xlsx";application.configService.writeDimensionsWorkbook(application.outputPath&name,application.configService.getAmcDimensions(),"Dimensions");application.outputs.register(name,"config");redirectTo("/download/"&urlEncodedFormat(name));}
if(path=="/get_amc_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getAmcPrices(),defaults:application.configService.amcDefaults()});}
if(path=="/set_amc_prices"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();if(d.reset?:false)application.configService.resetAmcPrices();else application.configService.saveAmcPrices(d.prices?:d);audit("config.amc_prices","config","amc_prices",{reset:d.reset?:false,prices:d.prices?:d});jsonOut({ok:true,prices:application.configService.getAmcPrices(),defaults:application.configService.amcDefaults()});}catch(any e){apiFail(e);}}
if(path=="/get_philips_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getPhilipsPrices(),defaults:application.configService.philipsDefaults()});}
if(path=="/set_philips_prices"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();if(d.reset?:false)application.configService.resetPhilipsPrices();else application.configService.savePhilipsPrices(d.prices?:d);audit("config.philips_prices","config","philips_prices",{reset:d.reset?:false,prices:d.prices?:d});jsonOut({ok:true,prices:application.configService.getPhilipsPrices(),defaults:application.configService.philipsDefaults()});}catch(any e){apiFail(e);}}
if(path=="/get_tcl_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getTclPrices(),defaults:application.configService.tclDefaults()});}
if(path=="/set_tcl_prices"){requireAccess("invoice-generator","config");requirePost();try{d=bodyJson();if(d.reset?:false)application.configService.resetTclPrices();else application.configService.saveTclPrices(d.prices?:d);audit("config.tcl_prices","config","tcl_prices",{reset:d.reset?:false,prices:d.prices?:d});jsonOut({ok:true,prices:application.configService.getTclPrices(),defaults:application.configService.tclDefaults()});}catch(any e){apiFail(e);}}

// Workshop
if(path=="/sanitize"&&method=="POST"){requireAccess("invoice-generator","promethean");try{raw=saveUploadAny(["raw_file","file","raw","repair_file"],["xlsx"]);a=application.invoice.analyzeWorkshop(raw,valForm(["date_from","from","date-from"]),valForm(["date_to","to","date-to"]));a.master_path=saveUploadAny(["prev_invoiced"],["xlsx"]);a.shipping_path=saveUploadAny(["shipping"],["csv"]);a.fedex_path="";if(len(form.fedex?:""))a.fedex_path=saveUploadAny(["fedex"],["xlsx"]);a.date_from=form.date_from;a.date_to=form.date_to;a._meta=duplicate(form);session.workshop=a;structDelete(session,"workshop_done");jsonOut({ok:true,clean_records:arrayLen(a.clean),fedex_uploaded:len(a.fedex_path)>0,total_records:a.total_records,issues:a.issues,issue_count:a.issue_count,auto_count:a.auto_count,auto_corrections:a.auto_corrections});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/generate"&&method=="POST"){requireAccess("invoice-generator","promethean");try{
    corr={};if(len(form.corrections?:""))corr=deserializeJson(form.corrections);
    if(lCase(form.mode?:"raw")=="legacy"){
        repair=saveUploadAny(["repair"],["xlsx"]);master=saveUploadAny(["prev_invoiced"],["xlsx"]);shipping=saveUploadAny(["shipping"],["csv"]);
        meta={call_id:form.call_id?:"C1413671",customer:form.customer?:"Promethean",invoice_date:form.invoice_date?:form.date_to,completed_date:form.completed_date?:form.date_to};
        session.workshop=application.invoice.analyzeWorkshopLegacy(repair,master,shipping,form.date_from,form.date_to,meta);
    }
    if(!structKeyExists(session,"workshop"))throw(type="Logicore.State",message="No Workshop analysis is active. Validate the source file again.");
    result=application.invoice.buildWorkshop(session.workshop,corr,safeOutputName(form.output_filename?:"","Promethean_Workshop_Invoice"));session.workshop_done=result;audit("invoice.workshop_built","output",result.filename,{subtotal:result.subtotal,total:result.total,depot_count:result.depot_count,triage_count:result.triage_count,excluded_count:result.excluded_count,mode:lCase(form.mode?:"raw")});jsonOut({ok:true,output:result.filename});
}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream"){requireAccess("invoice-generator","promethean");d=session.workshop_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// Storage
if(path=="/analyze_storage"&&method=="POST"){requireAccess("invoice-generator","promethean");try{inv=saveUploadAny(["inventory","inventory_file"],["csv"]);sh=saveUploadAny(["shipping","shipping_file"],["csv"]);rc=saveUploadAny(["receipt","receipts","receipt_file"],["csv"]);fx=saveUploadAny(["fedex","fedex_file"],["xlsx"]);whitelist="";try{whitelist=saveUploadAny(["whitelist","whitelist_file"],["xlsx"]);}catch(any ignored){}a=application.invoice.analyzeStorage(inv,sh,rc,fx,val(valForm(["pallet_count","pallets"],0)),valForm(["date_from","from"]),valForm(["date_to","to"]),whitelist);a._meta=duplicate(form);session.storage=a;structDelete(session,"storage_done");jsonOut({ok:true,logs:[],unmatched_count:arrayLen(a.unmatched),units_received_count:arrayLen(a.units_received),programming_rows:arrayLen(a.programming),unit_storage_count:arrayLen(a.unit_storage),unit_receipt_count:arrayLen(a.units_received),unit_picks_count:a.unit_picks_count,small_part_picks:a.small_part_picks,pallet_count:a.pallet_count,auto_spc_count:arrayLen(a.auto_spc_rows),unmatched:a.unmatched,review_unmatched:a.unmatched});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_storage"&&method=="POST"){requireAccess("invoice-generator","promethean");try{if(!structKeyExists(session,"storage"))throw(type="Logicore.State",message="No Storage analysis is active.");include=[];includeRaw=form.confirmed_rows?:form.include_unmatched?:"";if(!len(includeRaw)&&findNoCase("json",cgi.content_type?:"")){jsonBody=bodyJson();if(isStruct(jsonBody))includeRaw=jsonBody.confirmed_rows?:jsonBody.include_unmatched?:"";}if(isSimpleValue(includeRaw)&&len(includeRaw))includeRaw=deserializeJson(includeRaw);if(isArray(includeRaw))include=includeRaw;r=application.invoice.buildStorage(session.storage,safeOutputName(session.storage._meta.output_filename?:"","Promethean_Storage_Invoice"),include);session.storage_done=r;audit("invoice.storage_built","output",r.filename,{subtotal:r.subtotal,total:r.total});jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_storage"){requireAccess("invoice-generator","promethean");d=session.storage_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// FedEx shipment upload
if(path=="/analyze_fedex_shipment"&&method=="POST"){requireAccess("invoice-generator","promethean");try{raw=saveUploadAny(["raw","file","fedex_raw"],["xlsx"]);a=application.invoice.analyzeFedexShipment(raw,valForm(["period_label","period"],dateFormat(now(),"mmmm yyyy")),valForm(["call_date","date"],dateFormat(now(),"yyyy-mm-dd")));a._meta=duplicate(form);session.fedex=a;structDelete(session,"fedex_done");jsonOut({ok:true,logs:[],row_count:arrayLen(a.rows),defaulted_rows:a.defaulted_rows,skipped_rows:a.skipped_rows,total_price:a.total_price});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/build_fedex_shipment"&&method=="POST"){requireAccess("invoice-generator","promethean");try{if(!structKeyExists(session,"fedex"))throw(type="Logicore.State",message="No FedEx analysis is active.");r=application.invoice.buildFedexShipment(session.fedex,safeOutputName(session.fedex._meta.output_filename?:"","FedEx_Shipment_Upload"));session.fedex_done=r;audit("invoice.fedex_built","output",r.filename,{total_price:r.total_price,row_count:r.row_count});jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_fedex_shipment"){requireAccess("invoice-generator","promethean");d=session.fedex_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// Philips
if(path=="/analyze_philips"&&method=="POST"){requireAccess("invoice-generator","philips");try{report=saveUploadAny(["report","file","month_end_report"],["xlsx"]);a=application.invoice.analyzePhilips(report,val(valForm(["parts_sqft","parts_square_footage"],0)));session.philips=a;session.philips_meta=duplicate(form);structDelete(session,"philips_done");jsonOut({ok:true,logs:[],inbound_count:a.inbound_count,outbound_count:a.outbound_count,repair_count:a.repair_count,harvest_count:a.harvest_count,missing_dimension_models:a.missing_dimension_models,demo_total_sqft:a.demo_total_sqft,service_total_sqft:a.service_total_sqft});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/generate_report_and_analyze"&&method=="POST"){requireAccess("invoice-generator","philips");try{raw=saveUploadAny(["raw_data","raw","file"],["xlsx"]);pr=application.philipsReport.buildFromRaw(raw,valForm(["period_start"]),valForm(["period_end"]),valForm(["report_filename"],""));application.outputs.register(pr.filename,"philips");parts=val(valForm(["parts_sqft","parts_square_footage"],0));a=application.invoice.analyzePhilips(pr.path,parts);a.report_filename=pr.filename;session.philips=a;structDelete(session,"philips_done");session.philips_meta={invoice_title:valForm(["invoice_title"],"TPV-Philips Warehouse & Repair"),output_filename:valForm(["output_filename"],"")};jsonOut({ok:true,logs:[],report_filename:pr.filename,flagged_received_count:pr.flagged_received_count,pending_repairs_count:pr.pending_repairs_count,inbound_count:a.inbound_count,outbound_count:a.outbound_count,repair_count:a.repair_count,harvest_count:a.harvest_count,missing_dimension_models:a.missing_dimension_models,missing_repair_models:a.missing_repair_models,demo_total_sqft:a.demo_total_sqft,service_total_sqft:a.service_total_sqft});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_philips"&&method=="POST"){requireAccess("invoice-generator","philips");try{if(!structKeyExists(session,"philips"))throw(type="Logicore.State",message="No Philips analysis is active.");body=bodyJson();for(model in (body.dimensions?:{})){sqft=body.dimensions[model];if(len(sqft&""))application.configService.addPhilipsDimension(model,sqft);}reportFilename=session.philips.report_filename?:"";session.philips=application.invoice.analyzePhilips(session.philips.report_path,session.philips.parts_sqft_manual);meta=session.philips_meta?:{};invoiceTitle=valForm(["invoice_title"],meta.invoice_title?:"TPV Philips Warehouse Invoice");outputBase=valForm(["output_filename"],meta.output_filename?:"");r=application.invoice.buildPhilips(session.philips,invoiceTitle,safeOutputName(outputBase,"TPV_Philips_Warehouse_Invoice"));r.report_filename=reportFilename;r.excluded_count=arrayLen(session.philips.excluded);session.philips_done=r;audit("invoice.philips_built","output",r.filename,{subtotal:r.subtotal,total:r.total,manual_dimensions:body.dimensions?:{}});jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_philips"){requireAccess("invoice-generator","philips");d=session.philips_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// AMC
if(path=="/analyze_amc"&&method=="POST"){requireAccess("invoice-generator","amc");try{rec=saveUploadAny(["receiving"],["xlsx"]);ship=saveUploadAny(["shipping"],["xlsx"]);inv=saveUploadAny(["inventory"],["xlsx"]);a=application.invoice.analyzeAMC(rec,ship,inv,valForm(["date_from","period_start","from"]),valForm(["date_to","period_end","to"]));a._meta=duplicate(form);a._sources={receiving:rec,shipping:ship,inventory:inv};session.amc=a;structDelete(session,"amc_done");jsonOut({ok:true,logs:[],receipt_count:a.receipt_count,ship_count:a.ship_count,total_sqft:a.total_sqft,additional_sqft:a.additional_sqft,missing_dimension_models:a.missing_dimension_models});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_amc"&&method=="POST"){requireAccess("invoice-generator","amc");try{if(!structKeyExists(session,"amc"))throw(type="Logicore.State",message="No AMC analysis is active.");body=bodyJson();for(model in (body.dimensions?:{})){sqft=body.dimensions[model];if(len(sqft&""))application.configService.addAmcDimension(model,sqft);}meta=session.amc._meta;src=session.amc._sources;a=application.invoice.analyzeAMC(src.receiving,src.shipping,src.inventory,session.amc.period_start,session.amc.period_end);r=application.invoice.buildAMC(a,meta.invoice_title?:"AMC Warehouse Invoice",safeOutputName(meta.output_filename?:"","AMC_Warehouse_Invoice"));r.excluded_count=arrayLen(a.excluded);session.amc_done=r;audit("invoice.amc_built","output",r.filename,{subtotal:r.subtotal,total:r.total,manual_dimensions:body.dimensions?:{}});jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_amc"){requireAccess("invoice-generator","amc");d=session.amc_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// TCL
if(path=="/analyze_tcl"&&method=="POST"){requireAccess("invoice-generator","tcl");try{inv=saveUploadAny(["inventory","file"],["xlsx"]);a=application.invoice.analyzeTCL(inv,valForm(["date_from","from"]),valForm(["date_to","to"]));a._meta=duplicate(form);session.tcl=a;structDelete(session,"tcl_done");jsonOut({ok:true,logs:[],unit_groups:a.unit_groups,part_groups:a.part_groups,unit_count:a.unit_count,part_count:a.part_count});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_tcl"&&method=="POST"){requireAccess("invoice-generator","tcl");try{if(!structKeyExists(session,"tcl"))throw(type="Logicore.State",message="No TCL analysis is active.");body=bodyJson();units=body.unit_breakdowns?:{};boxes=body.box_breakdowns?:{};valid=application.invoice.validateTCL(session.tcl,units,boxes);if(arrayLen(valid.errors))jsonOut({ok:false,error:"Fix the highlighted breakdowns",field_errors:valid.errors},400);r=application.invoice.buildTCL(session.tcl,units,boxes,safeOutputName(session.tcl._meta.output_filename?:"","TCL_Warehouse_Invoice"));session.tcl_done=r;audit("invoice.tcl_built","output",r.filename,{subtotal:r.subtotal,total:r.total});jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_tcl"){requireAccess("invoice-generator","tcl");d=session.tcl_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// SMS NonConforming API
if(path=="/nonconforming/api/items"&&method=="GET"){u=requireAccess("sms-nonconforming");data=application.nonconforming.listItems(valUrl("q",""),valUrl("status",""),min(max(val(valUrl("limit",200)),0),1000),max(val(valUrl("offset",0)),0));data.ok=true;data.next_number_preview=application.nonconforming.previewNextNumber(application.auth.initialsFor(u));jsonOut(data);}
if(path=="/nonconforming/api/items"&&method=="POST"){u=requireAccess("sms-nonconforming");try{item=application.nonconforming.addItem(bodyJson(),u,application.auth.initialsFor(u));audit("nonconforming.create","nc_item",item.id?:"",{number:item.number?:"",model:item.model?:"",serial:item.serial?:""});jsonOut({ok:true,item:item});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/nonconforming/api/next_number"||path=="/nonconforming/api/next-number"){u=requireAccess("sms-nonconforming");preview=application.nonconforming.previewNextNumber(application.auth.initialsFor(u));jsonOut({ok:true,preview:preview,next_number:preview});}
if(path=="/nonconforming/api/export"){requireAccess("sms-nonconforming");data=application.nonconforming.listItems(valUrl("q",""),valUrl("status",""),100000,0);name=application.nonconforming.buildExport(data.items);application.outputs.register(name,"sms-nonconforming");audit("nonconforming.export","output",name,{rows:arrayLen(data.items),q:valUrl("q",""),status:valUrl("status","")});redirectTo("/download/"&urlEncodedFormat(name));}
nm=reFind("^/nonconforming/api/items/([0-9]+)(/label)?$",path,1,true);
if(nm.len[1]){requireAccess("sms-nonconforming");id=val(mid(path,nm.pos[2],nm.len[2]));isLabel=nm.len[3]>0;if(isLabel){item=application.nonconforming.getItem(id);if(!structCount(item))jsonOut({ok:false,error:"Not found"},404);zpl=application.nonconforming.buildZpl(item);if(valUrl("download",0)==1){cfheader(name="Content-Disposition",value='attachment; filename="'&item.number&'.zpl"');cfcontent(type="application/octet-stream",reset=true);writeOutput(zpl);abort;}jsonOut({ok:true,number:item.number,zpl:zpl});}if(method=="GET"){item=application.nonconforming.getItem(id);if(!structCount(item))jsonOut({ok:false,error:"Not found"},404);jsonOut({ok:true,item:item});}if(method=="PUT"||method=="PATCH"){try{changes=bodyJson();item=application.nonconforming.updateItem(id,changes);if(!structCount(item))jsonOut({ok:false,error:"Not found"},404);audit("nonconforming.update","nc_item",id,{number:item.number?:"",fields:changes});jsonOut({ok:true,item:item});}catch(any e){jsonOut({ok:false,error:e.message},400);}}if(method=="DELETE"){existing=application.nonconforming.getItem(id);deleted=application.nonconforming.deleteItem(id);if(!deleted)jsonOut({ok:false,error:"Not found"},404);audit("nonconforming.delete","nc_item",id,{number:existing.number?:"",model:existing.model?:"",serial:existing.serial?:""});jsonOut({ok:true});}}

// Download generated files with persistent ownership markers.
dm=reFind("^/download/(.+)$",path,1,true);
if(dm.len[1]){u=requireLogin();filename=urlDecode(mid(path,dm.pos[2],dm.len[2]));subsection=application.outputs.subsection(filename);if(!len(subsection))jsonOut({ok:false,error:"File not found."},404);allowed=subsection=="sms-nonconforming"?application.auth.hasAccess(u,"sms-nonconforming"):application.auth.hasAccess(u,"invoice-generator",subsection);if(!allowed)jsonOut({ok:false,error:"Not authorized."},403);real=application.outputs.resolve(filename);if(!len(real))jsonOut({ok:false,error:"File not found."},404);audit("file.download","output",filename,{subsection:subsection});cfheader(name="Content-Disposition",value='attachment; filename="'&getFileFromPath(real)&'"');cfcontent(file=real,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}

jsonOut({ok:false,error:"Not found",path:path},404);
</cfscript>
