<cfscript>
function ttBase(required string title){
    var sub=request.ttSub?:"/";var nav='<div class="sidebar-sub" aria-label="Training Tracker pages"><a class="side-sublink '&((sub=="/"||left(sub,6)=="/week/"||left(sub,9)=="/session/"||left(sub,7)=="/topic/"||left(sub,7)=="/video/")?'active':'')&'" href="/training-tracker/">Courses</a><a class="side-sublink '&(sub=="/people"||left(sub,8)=="/people/"?'active':'')&'" href="/training-tracker/people">Roster</a>';
    if(request.ttCanEdit)nav&='<a class="side-sublink '&(left(sub,8)=="/reports"?'active':'')&'" href="/training-tracker/reports">Reports</a>';
    if(request.ttIsAdmin)nav&='<a class="side-sublink '&(left(sub,6)=="/admin"?'active':'')&'" href="/training-tracker/admin">Content Settings</a>';
    return workspaceShellStart(request.ttUser,"training-tracker",arguments.title,"",nav&'</div>');
}
function ttEnd(){return workspaceShellEnd();}
function ttBackWeek(required numeric id){return '/training-tracker/week/'&arguments.id;}
function ttRequireEdit(){if(!request.ttCanEdit)htmlOut(ttBase("Access denied")&'<p>You do not have permission to edit Training Tracker.</p>'&ttEnd(),403);}
function ttRequireAdmin(){if(!request.ttIsAdmin)htmlOut(ttBase("Access denied")&'<p>Training Tracker administrator access is required.</p>'&ttEnd(),403);}
function ttSessionIdFrom(required struct match,required numeric index){return val(mid(request.ttSub,match.pos[index],match.len[index]));}
function ttSettingsLabel(required string key){
    var label=listLast(arguments.key,".");
    label=replace(label,"_"," ","all");
    return uCase(left(label,1))&mid(label,2);
}
function ttSettingsField(required string key,required string value){
    var label=ttSettingsLabel(arguments.key);
    var control=len(arguments.value)>90?'<textarea name="'&encodeForHtmlAttribute(arguments.key)&'" rows="3">'&encodeForHtml(arguments.value)&'</textarea>':'<input name="'&encodeForHtmlAttribute(arguments.key)&'" value="'&encodeForHtmlAttribute(arguments.value)&'">';
    return '<label class="settings-field"><span class="settings-field-copy"><strong>'&encodeForHtml(label)&'</strong><code>'&encodeForHtml(arguments.key)&'</code></span>'&control&'</label>';
}
function ttContentFields(required struct values){
    var groups=[
        {title:"General",description:"Training Tracker name, tagline, and footer copy.",prefixes:["site."]},
        {title:"Navigation",description:"Labels used in the Training Tracker sidebar.",prefixes:["nav."]},
        {title:"Courses & curriculum",description:"Course, topic, and curriculum page headings and actions.",prefixes:["index.","week."]},
        {title:"Sessions & sign-off",description:"Session workflow, attendance, and sign-off actions.",prefixes:["session."]},
        {title:"Roster",description:"Employee roster headings and actions.",prefixes:["people."]},
        {title:"Reports",description:"Reporting and export labels.",prefixes:["reports."]},
        {title:"Administration",description:"Administrator-facing headings.",prefixes:["admin."]}
    ];
    var rendered={};var h='<div class="settings-groups">';
    for(var group in groups){
        var keys=[];
        for(var k in arguments.values){
            if(k=="account.heading")continue;
            for(var prefix in group.prefixes)if(left(k,len(prefix))==prefix){arrayAppend(keys,k);break;}
        }
        if(!arrayLen(keys))continue;
        arraySort(keys,"textnocase");
        h&='<section class="settings-group"><div class="settings-group-header"><div><h3>'&encodeForHtml(group.title)&'</h3><p>'&encodeForHtml(group.description)&'</p></div><span>'&arrayLen(keys)&' field'&(arrayLen(keys)==1?'':'s')&'</span></div><div class="settings-group-fields">';
        for(var key in keys){h&=ttSettingsField(key,arguments.values[key]&"");rendered[key]=true;}
        h&='</div></section>';
    }
    var other=[];for(var unknown in arguments.values)if(unknown!="account.heading"&&!structKeyExists(rendered,unknown))arrayAppend(other,unknown);
    if(arrayLen(other)){arraySort(other,"textnocase");h&='<section class="settings-group"><div class="settings-group-header"><div><h3>Additional content</h3><p>Custom content entries not included in the standard groups.</p></div><span>'&arrayLen(other)&' fields</span></div><div class="settings-group-fields">';for(var extra in other)h&=ttSettingsField(extra,arguments.values[extra]&"");h&='</div></section>';}
    return h&'</div>';
}

request.ttUser=requireLogin();request.ttRole=application.auth.getRole(request.ttUser,"training-tracker");if(!len(request.ttRole))redirectTo("/");request.ttCanEdit=listFindNoCase("admin,editor",request.ttRole)>0;request.ttIsAdmin=request.ttRole=="admin";request.ttSub=removeChars(path,1,len("/training-tracker"));if(!len(request.ttSub))request.ttSub="/";sub=request.ttSub;

// Dashboard / weeks
if(sub=="/"&&method=="GET"){
    c=application.training.content();weeks=application.training.weeks();h=ttBase(c["site.name"]?:"Training Ledger")&'<p class="muted">'&encodeForHtml(c["site.tagline"]?:"training curriculum by date")&'</p><h2>'&encodeForHtml(c["index.heading"]?:"Training Courses by Date")&'</h2>';
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/new"><input name="title" placeholder="Course title" required><input type="date" name="start_date" required><button>'&encodeForHtml(c["index.new_week_btn"]?:"+ New Course")&'</button></form></div>';
    if(!arrayLen(weeks))h&='<div class="card"><strong>'&encodeForHtml(c["index.empty_title"]?:"No entries yet")&'</strong><p>'&encodeForHtml(c["index.empty_body"]?:"Add or import your first dated training course.")&'</p></div>';
    for(w in weeks)h&='<div class="card"><a href="/training-tracker/week/'&w.id&'"><strong>'&encodeForHtml(len(w.start_date?:"")?dateFormat(w.start_date,"mmmm d, yyyy"):"Undated")&' &middot; '&encodeForHtml(w.title)&'</strong></a><div class="muted">'&w.topic_count&' topics &middot; '&w.session_count&' sessions &middot; '&w.signed_count&' / '&w.attended_count&' signed</div></div>';
    htmlOut(h&'<p class="muted">'&encodeForHtml(c["site.footer"]?:"")&'</p>'&ttEnd());
}
if(sub=="/week/new"&&method=="POST"){ttRequireEdit();id=application.training.createWeek(form.title?:"",form.start_date?:"",form.notes?:"");redirectTo(ttBackWeek(id));}
wm=reFind("^/week/([0-9]+)$",sub,1,true);
if(wm.len[1]&&method=="GET"){
    wid=ttSessionIdFrom(wm,2);w=application.training.week(wid);if(!structCount(w))htmlOut(ttBase("Not found")&'<p>Training course not found.</p>'&ttEnd(),404);
    h=ttBase(w.title)&'<div class="card"><strong>Training date:</strong> '&encodeForHtml(w.start_date?:"")&'<br><strong>Notes:</strong> '&encodeForHtml(w.notes?:"")&'<br><strong>Progress:</strong> '&w.signed&' signed / '&w.attended&' attended</div>';
    if(request.ttCanEdit)h&='<div class="card"><h2>Edit course</h2><form method="post" action="/training-tracker/week/'&wid&'/edit"><input name="title" value="'&encodeForHtmlAttribute(w.title)&'" required><input type="date" name="start_date" value="'&encodeForHtmlAttribute(w.start_date?:"")&'" required><textarea name="notes">'&encodeForHtml(w.notes?:"")&'</textarea><button>Save</button></form><form method="post" action="/training-tracker/week/'&wid&'/delete" style="margin-top:8px"><button class="danger">Delete course</button></form></div>';
    h&='<h2>Topics & Lesson Plans</h2>';for(t in w.topics){h&='<div class="card"><strong>'&encodeForHtml(t.title)&'</strong><p>'&encodeForHtml(t.lesson_plan?:"")&'</p><pre style="white-space:pre-wrap">'&encodeForHtml(t.key_points?:"")&'</pre>';if(arrayLen(t.videos)){h&='<ul>';for(v in t.videos)h&='<li><a href="'&encodeForHtmlAttribute(v.url)&'" target="_blank" rel="noopener noreferrer">'&encodeForHtml(v.title?:v.url)&'</a>'&(request.ttCanEdit?' <form class="inline" method="post" action="/training-tracker/video/'&v.id&'/delete"><button class="danger">Delete</button></form>':'')&'</li>';h&='</ul>';}if(request.ttCanEdit)h&='<form method="post" action="/training-tracker/topic/'&t.id&'/edit"><input name="title" aria-label="Topic title" value="'&encodeForHtmlAttribute(t.title)&'"><textarea name="lesson_plan" aria-label="Lesson plan" placeholder="Lesson plan">'&encodeForHtml(t.lesson_plan?:"")&'</textarea><textarea name="key_points" aria-label="Key points" placeholder="Key points, one per line">'&encodeForHtml(t.key_points?:"")&'</textarea><button>Save topic</button></form><form class="inline" method="post" action="/training-tracker/topic/'&t.id&'/delete"><button class="danger">Delete topic</button></form><form method="post" action="/training-tracker/topic/'&t.id&'/video/add"><input name="video_title" aria-label="Video label" placeholder="Video label"><input name="url" type="url" aria-label="Video URL" placeholder="https://..." required><button>Link video</button></form>';h&='</div>';}
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/'&wid&'/topic/new"><input name="title" placeholder="Topic" required><textarea name="lesson_plan" placeholder="Lesson plan"></textarea><textarea name="key_points" placeholder="Key points, one per line"></textarea><button>+ Add Topic</button></form></div>';
    h&='<h2>Sessions</h2>';for(s in w.sessions){h&='<div class="card"><a href="/training-tracker/session/'&s.id&'"><strong>'&encodeForHtml(s.trainer_name)&'</strong></a> &middot; '&encodeForHtml(s.session_date?:"")&' &middot; '&encodeForHtml(s.location?:"")&'<br><span class="muted">'&s.attended_count&' attended &middot; '&s.signed_count&' signed</span>';if(structCount(s.upload?:{}))h&='<br><a href="/training-tracker/session/'&s.id&'/signoff/view">View uploaded signed sheet</a>';if(request.ttCanEdit)h&='<form method="post" action="/training-tracker/session/'&s.id&'/edit"><input name="trainer_name" value="'&encodeForHtmlAttribute(s.trainer_name)&'"><input type="date" name="session_date" value="'&encodeForHtmlAttribute(s.session_date?:"")&'"><input name="location" value="'&encodeForHtmlAttribute(s.location?:"")&'"><button>Save</button></form><form class="inline" method="post" action="/training-tracker/session/'&s.id&'/delete"><button class="danger">Delete</button></form>';h&='</div>';}
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/'&wid&'/session/new"><input name="trainer_name" placeholder="Trainer"><input type="date" name="session_date"><input name="location" placeholder="Location"><button>+ New Session</button></form></div>';
    htmlOut(h&ttEnd());
}
we=reFind("^/week/([0-9]+)/(edit|delete)$",sub,1,true);if(we.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(we,2);action=mid(sub,we.pos[3],we.len[3]);if(action=="edit"){application.training.updateWeek(wid,form.title?:"",form.start_date?:"",form.notes?:"");redirectTo(ttBackWeek(wid));}application.training.deleteWeek(wid);redirectTo("/training-tracker/");}

// Sessions
sn=reFind("^/week/([0-9]+)/session/new$",sub,1,true);if(sn.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(sn,2);application.training.createSession(wid,form.trainer_name?:"",form.session_date?:"",form.location?:"");redirectTo(ttBackWeek(wid));}
se=reFind("^/session/([0-9]+)/(edit|delete)$",sub,1,true);if(se.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(se,2);sess=application.training.session(sid);if(!structCount(sess))htmlOut("Not found",404);action=mid(sub,se.pos[3],se.len[3]);if(action=="edit")application.training.updateSession(sid,form.trainer_name?:"",form.session_date?:"",form.location?:"");else application.training.deleteSession(sid);redirectTo(ttBackWeek(sess.week_id));}
sg=reFind("^/session/([0-9]+)$",sub,1,true);if(sg.len[1]&&method=="GET"){sid=ttSessionIdFrom(sg,2);sess=application.training.session(sid);if(!structCount(sess))htmlOut(ttBase("Not found")&'<p>Session not found.</p>'&ttEnd(),404);h=ttBase("Sign-off - "&sess.trainer_name)&'<p><a href="'&ttBackWeek(sess.week_id)&'">&larr; '&encodeForHtml(len(sess.week_start_date?:"")?dateFormat(sess.week_start_date,"mmmm d, yyyy"):"Course")&'</a></p><div class="card"><strong>'&encodeForHtml(sess.week_title)&'</strong><br>'&encodeForHtml(sess.session_date?:"")&' &middot; '&encodeForHtml(sess.location?:"")&'</div><table><tr><th>Name</th><th>Attended</th><th>Digital signature</th></tr>';for(a in sess.attendance){h&='<tr><td>'&encodeForHtml(a.name)&'</td><td>'&(val(a.attended)?'Yes':'No')&'</td><td>'&encodeForHtml(a.signature?:"")&'</td></tr>';}h&='</table>';if(request.ttCanEdit){h&='<div class="card"><h2>Attendance & digital sign-off</h2>';for(a in sess.attendance)h&='<form method="post" action="/training-tracker/session/'&sid&'/attendance/'&a.person_id&'" style="margin:7px 0"><strong>'&encodeForHtml(a.name)&'</strong> <label><input type="checkbox" name="attended" '&(val(a.attended)?'checked':'')&'> Attended</label> <input name="signature" value="'&encodeForHtmlAttribute(a.signature?:"")&'" placeholder="Signature"><button>Save</button></form>';h&='<p><a class="btn" href="/training-tracker/session/'&sid&'/signoff/download">Download Sign-off Template</a></p><form method="post" enctype="multipart/form-data" action="/training-tracker/session/'&sid&'/signoff/upload"><input type="file" name="signoff_file" accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.heic" required><button>Upload Signed Sheet</button></form>';if(structCount(sess.upload?:{}))h&='<p><a href="/training-tracker/session/'&sid&'/signoff/view">View uploaded sheet</a></p><form method="post" action="/training-tracker/session/'&sid&'/signoff/remove"><button class="danger">Remove uploaded sheet</button></form>';h&='</div>';}htmlOut(h&ttEnd());}
oldAttendance=reFind("^/session/([0-9]+)/attendance/toggle$",sub,1,true);if(oldAttendance.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(oldAttendance,2);application.training.toggleAttendance(sid,val(form.person_id?:0),(form.attended?:"")=="1");jsonOut({ok:true});}
newAttendance=reFind("^/session/([0-9]+)/attendance/([0-9]+)$",sub,1,true);if(newAttendance.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(newAttendance,2);pid=ttSessionIdFrom(newAttendance,3);application.training.setAttendance(sid,pid,structKeyExists(form,"attended"));if(len(trim(form.signature?:"")))application.training.sign(sid,pid,form.signature);redirectTo("/training-tracker/session/"&sid);}

// Topics / videos
tn=reFind("^/week/([0-9]+)/topic/new$",sub,1,true);if(tn.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(tn,2);application.training.createTopic(wid,form.title?:"",form.lesson_plan?:"",form.key_points?:"");redirectTo(ttBackWeek(wid));}
te=reFind("^/topic/([0-9]+)/(edit|delete)$",sub,1,true);if(te.len[1]&&method=="POST"){ttRequireEdit();tid=ttSessionIdFrom(te,2);topic=application.training.topic(tid);if(!structCount(topic))htmlOut("Not found",404);action=mid(sub,te.pos[3],te.len[3]);if(action=="edit")application.training.updateTopic(tid,form.title?:"",form.lesson_plan?:"",form.key_points?:"");else application.training.deleteTopic(tid);redirectTo(ttBackWeek(topic.week_id));}
va=reFind("^/topic/([0-9]+)/video/add$",sub,1,true);if(va.len[1]&&method=="POST"){ttRequireEdit();tid=ttSessionIdFrom(va,2);topic=application.training.topic(tid);if(!structCount(topic))htmlOut(ttBase("Not found")&'<p>Training topic not found.</p>'&ttEnd(),404);if(!reFindNoCase("^https?://",trim(form.url?:"")))htmlOut(ttBase("Invalid video link")&'<div class="card"><p>Video links must begin with <code>http://</code> or <code>https://</code>.</p><p><a href="'&ttBackWeek(topic.week_id)&'">Return to the training course</a></p></div>'&ttEnd(),400);application.training.addVideo(tid,form.video_title?:"",form.url?:"");redirectTo(ttBackWeek(topic.week_id));}
vd=reFind("^/video/([0-9]+)/delete$",sub,1,true);if(vd.len[1]&&method=="POST"){ttRequireEdit();vid=ttSessionIdFrom(vd,2);v=application.training.video(vid);if(!structCount(v))htmlOut(ttBase("Not found")&'<p>Video not found.</p>'&ttEnd(),404);application.training.deleteVideo(vid);redirectTo(ttBackWeek(v.week_id));}

// Roster
if(sub=="/people"&&method=="GET"){h=ttBase("Roster");for(p in application.training.people())h&='<div class="card"><strong>'&encodeForHtml(p.name)&'</strong> &middot; '&encodeForHtml(p.email?:"")&(request.ttCanEdit?' <form class="inline" method="post" action="/training-tracker/people/'&p.id&'/delete"><button class="danger">Delete</button></form>':'')&'</div>';if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/people/add"><input name="name" required placeholder="Name"><input name="email" placeholder="Email"><button>+ Add Person</button></form></div>';htmlOut(h&ttEnd());}
if((sub=="/people/add"||sub=="/people")&&method=="POST"){ttRequireEdit();application.training.addPerson(form.name?:"",form.email?:"");redirectTo("/training-tracker/people");}
pd=reFind("^/people/([0-9]+)/delete$",sub,1,true);if(pd.len[1]&&method=="POST"){ttRequireEdit();application.training.deletePerson(ttSessionIdFrom(pd,2));redirectTo("/training-tracker/people");}

// Sign-off scans and template
sd=reFind("^/session/([0-9]+)/signoff/(download|upload|view|remove)$",sub,1,true);if(sd.len[1]){ttRequireEdit();sid=ttSessionIdFrom(sd,2);action=mid(sub,sd.pos[3],sd.len[3]);sess=application.training.session(sid);if(!structCount(sess))htmlOut("Not found",404);
    if(action=="download"&&method=="GET"){attendees=[];for(a in sess.attendance)if(val(a.attended))arrayAppend(attendees,a);filename=(len(sess.week_start_date?:"")?dateFormat(sess.week_start_date,"yyyy-mm-dd"):"Training")&" Sign-off Template"&(sess.trainer_name!="Unassigned"?" - "&reReplace(sess.trainer_name,"[^A-Za-z0-9._ -]","_","all"):"")&".pdf";pdf=application.trainingPdf.build(sess,attendees);cfheader(name="Content-Disposition",value='attachment; filename="'&filename&'"');cfcontent(type="application/pdf",variable=pdf,reset=true);abort;}
    if(action=="upload"&&method=="POST"){f=fileUpload(application.uploadPath,"signoff_file","","makeunique",true,["pdf","png","jpg","jpeg","gif","webp","heic"]);try{application.training.saveSignoff(sid,f.serverDirectory&"/"&f.serverFile,f.clientFile,f.contentType?:"application/octet-stream",request.ttUser.username);}finally{try{fileDelete(f.serverDirectory&"/"&f.serverFile);}catch(any ignored){}}redirectTo(ttBackWeek(sess.week_id));}
    if(action=="view"&&method=="GET"){up=application.training.signoffUpload(sid);real=application.training.signoffPath(sid);if(!len(real))htmlOut("Not found",404);cfheader(name="Content-Disposition",value='inline; filename="'&getFileFromPath(up.original_filename?:up.filename)&'"');cfheader(name="Content-Security-Policy",value="sandbox");cfcontent(file=real,type=up.content_type?:"application/octet-stream",reset=true);abort;}
    if(action=="remove"&&method=="POST"){application.training.removeSignoff(sid);redirectTo(ttBackWeek(sess.week_id));}
}

// Reports
if(sub=="/reports"&&method=="GET"){ttRequireEdit();courses=application.training.weeks();h=ttBase("Reports")&'<div class="card"><h2>Signed Sign-off Sheets</h2><p class="muted">Choose a training-date range. Leave either date blank to use the earliest or latest available course date.</p><form method="get" action="/training-tracker/reports/signoff-zip"><label>From <input name="start_date" type="date"></label><label>To <input name="end_date" type="date"></label><button>Download ZIP</button></form></div><div class="card"><h2>Attendance Matrix</h2><form method="get" action="/training-tracker/reports/attendance-matrix"><label>From <input name="start_date" type="date"></label><label>To <input name="end_date" type="date"></label><button>Download Excel</button></form></div><p>'&arrayLen(courses)&' dated training courses available.</p>';htmlOut(h&ttEnd());}
if(sub=="/reports/signoff-zip"&&method=="GET"){ttRequireEdit();r=application.training.dateRange(url.start_date?:"",url.end_date?:"");if(!r.ok)htmlOut(ttBase("Reports")&'<p>'&encodeForHtml(r.error)&'</p>'&ttEnd(),400);fn=application.training.buildSignoffZip(r.lo,r.hi);if(!len(fn))htmlOut(ttBase("Reports")&'<p>No signed sheets have been uploaded for that range yet.</p>'&ttEnd(),404);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/zip",reset=true);abort;}
if(sub=="/reports/attendance-matrix"&&method=="GET"){ttRequireEdit();r=application.training.dateRange(url.start_date?:"",url.end_date?:"");if(!r.ok)htmlOut(ttBase("Reports")&'<p>'&encodeForHtml(r.error)&'</p>'&ttEnd(),400);fn=application.training.buildAttendanceMatrix(r.lo,r.hi);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}

// Admin-only legacy course import.
if(sub=="/admin/import/template"&&method=="GET"){ttRequireAdmin();templatePath=application.rootPath&"template/Training_Course_Import_Template.xlsx";if(!fileExists(templatePath))htmlOut("Import template not found",404);cfheader(name="Content-Disposition",value='attachment; filename="Training_Course_Import_Template.xlsx"');cfcontent(file=templatePath,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}
if(sub=="/admin/import"&&method=="POST"){ttRequireAdmin();if(!structKeyExists(form,"courses_file"))htmlOut(ttBase("Import courses")&'<div class="card"><p>Select an Excel workbook to import.</p></div>'&ttEnd(),400);uploaded=fileUpload(application.uploadPath,"courses_file","","makeunique",true,["xlsx","xls"]);try{session.trainingImportResult=application.trainingImport.importSpreadsheet(uploaded.serverDirectory&"/"&uploaded.serverFile);}finally{try{fileDelete(uploaded.serverDirectory&"/"&uploaded.serverFile);}catch(any ignored){}}redirectTo("/training-tracker/admin");}

// Training Tracker administration. The former account page duplicated the
// signed-in user and role already shown in the global portal shell.
if(sub=="/account"&&method=="GET")redirectTo("/training-tracker/");
if(sub=="/admin"&&method=="GET"){ttRequireAdmin();values=application.training.content();importNotice="";if(structKeyExists(session,"trainingImportResult")){ir=session.trainingImportResult;structDelete(session,"trainingImportResult");importNotice='<div class="card"><h2>Import complete</h2><p><strong>'&ir.courses_created&'</strong> courses created &middot; <strong>'&ir.courses_matched&'</strong> existing courses matched &middot; <strong>'&ir.topics_created&'</strong> topics &middot; <strong>'&ir.sessions_created&'</strong> sessions &middot; <strong>'&ir.videos_created&'</strong> videos.</p>';if(ir.skipped)importNotice&='<p class="muted">'&ir.skipped&' rows were skipped.</p>';if(arrayLen(ir.errors)){importNotice&='<ul>';for(importError in ir.errors)importNotice&='<li>'&encodeForHtml(importError)&'</li>';importNotice&='</ul>';}importNotice&='</div>';}h=ttBase("Content Settings")&'<section class="settings-group" style="margin-bottom:20px"><div class="settings-group-header"><div><h3>Legacy course import</h3><p>Download the standard workbook, add your historical courses, then upload it here. Rows are grouped by Course Date and Course Title.</p></div><span>Admin only</span></div><div class="settings-group-fields"><div class="settings-field"><p><a class="btn" href="/training-tracker/admin/import/template">Download Excel template</a></p><form method="post" enctype="multipart/form-data" action="/training-tracker/admin/import"><input type="file" name="courses_file" accept=".xlsx,.xls" required><button type="submit">Validate &amp; Import Courses</button></form><p class="muted">Required: Course Date and Course Title. Repeating both values adds more topics to the same course. Existing matches are not duplicated.</p></div></div></section>'&importNotice&'<div class="settings-intro"><div><span class="settings-eyebrow">Training Tracker administration</span><h2>Content library</h2><p>Manage the labels and explanatory copy used throughout Training Tracker. Theme selection is controlled globally from the top-right corner of every page.</p></div></div><form class="settings-form" method="post" action="/training-tracker/admin/content/save">'&ttContentFields(values)&'<div class="settings-savebar"><div><strong>Ready to publish?</strong><span>Saved changes take effect across Training Tracker immediately.</span></div><button type="submit">Save changes</button></div></form><div class="card danger-zone"><div><h2>Restore default content</h2><p class="muted">Replace all customized Training Tracker labels with the built-in USSI Nexus defaults.</p></div><form method="post" action="/training-tracker/admin/reset" onsubmit="return confirm(''Reset all Training Tracker content to its defaults?'')"><input type="hidden" name="scope" value="content"><button class="danger">Reset to defaults</button></form></div>';htmlOut(h&ttEnd());}
if(sub=="/admin/content/save"&&method=="POST"){ttRequireAdmin();application.training.saveContent(form);redirectTo("/training-tracker/admin##content");}
if(sub=="/admin/appearance/save"&&method=="POST"){ttRequireAdmin();application.training.saveTheme(form);redirectTo("/training-tracker/admin##appearance");}
if(sub=="/admin/reset"&&method=="POST"){ttRequireAdmin();if((form.scope?:"")=="appearance")application.training.resetTheme();else if((form.scope?:"")=="content")application.training.resetContent();redirectTo("/training-tracker/admin");}

// Compatibility aliases retained from the first Lucee conversion.
legacyWeek=reFind("^/weeks/([0-9]+)$",sub,1,true);if(legacyWeek.len[1])redirectTo("/training-tracker/week/"&ttSessionIdFrom(legacyWeek,2));
htmlOut(ttBase("Not found")&'<p>Training Tracker route not found.</p>'&ttEnd(),404);
</cfscript>
