component output=false {
    // Bearer keys for the /api/v1 integration surface. The plaintext key is
    // shown once at creation; only a SHA-256 hash is stored.
    function init(required string datasource) {
        variables.datasource = arguments.datasource;
        variables.scopes = ["inventory:read", "inventory:write", "invoices:read", "config:read"];
        queryExecute("CREATE TABLE IF NOT EXISTS api_keys (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, key_prefix VARCHAR(16) NOT NULL, key_hash VARCHAR(64) NOT NULL UNIQUE, scopes VARCHAR(500) NOT NULL, created_by VARCHAR(120), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, last_used_at TIMESTAMP, revoked_at TIMESTAMP)", {}, {datasource:variables.datasource});
        return this;
    }
    array function availableScopes() { return duplicate(variables.scopes); }

    struct function create(required string name, required array scopes, required string createdBy) {
        var n = trim(arguments.name); if (!len(n) || len(n) > 120) throw(type="Logicore.Validation", message="Key name is required (120 characters max).");
        var clean = [];
        for (var s in arguments.scopes) { if (!arrayFindNoCase(variables.scopes, s)) throw(type="Logicore.Validation", message="Unknown scope '" & s & "'."); if (!arrayFindNoCase(clean, s)) arrayAppend(clean, lCase(s)); }
        if (!arrayLen(clean)) throw(type="Logicore.Validation", message="Choose at least one scope.");
        var rnd = createObject("java", "java.security.SecureRandom").init();
        var prefix = lCase(left(binaryEncode(rnd.generateSeed(javaCast("int", 6)), "hex"), 8));
        var secret = lCase(binaryEncode(rnd.generateSeed(javaCast("int", 24)), "hex"));
        var key = "nxk_" & prefix & "_" & secret;
        var r = {};
        queryExecute("INSERT INTO api_keys(name,key_prefix,key_hash,scopes,created_by) VALUES(:n,:p,:h,:s,:c)", {n:n, p:prefix, h:hashKey(key), s:arrayToList(clean), c:left(arguments.createdBy, 120)}, {datasource:variables.datasource, result:"r"});
        var id = structKeyExists(r, "generatedKey") ? val(r.generatedKey) : val(queryExecute("SELECT MAX(id) id FROM api_keys", {}, {datasource:variables.datasource}).id[1]);
        return {id:id, name:n, prefix:prefix, scopes:clean, key:key};
    }
    private string function hashKey(required string key) { return lCase(hash(arguments.key, "SHA-256")); }

    // Returns the key record for a valid, unrevoked bearer value, else {}.
    struct function authenticate(required string bearer) {
        var k = trim(arguments.bearer);
        if (!reFind("^nxk_[a-f0-9]{8}_[a-f0-9]{48}$", k)) return {};
        var q = queryExecute("SELECT * FROM api_keys WHERE key_hash=:h AND revoked_at IS NULL", {h:hashKey(k)}, {datasource:variables.datasource});
        if (!q.recordCount) return {};
        queryExecute("UPDATE api_keys SET last_used_at=CURRENT_TIMESTAMP WHERE id=:id", {id:q.id[1]}, {datasource:variables.datasource});
        return {id:q.id[1], name:q.name[1], prefix:q.key_prefix[1], scopes:listToArray(q.scopes[1]), created_by:q.created_by[1]};
    }
    boolean function hasScope(required struct key, required string scope) { return structCount(arguments.key) && arrayFindNoCase(arguments.key.scopes ?: [], arguments.scope) > 0; }

    array function list() {
        var q = queryExecute("SELECT id,name,key_prefix,scopes,created_by,created_at,last_used_at,revoked_at FROM api_keys ORDER BY revoked_at NULLS FIRST, created_at DESC", {}, {datasource:variables.datasource});
        var out = []; for (var i = 1; i <= q.recordCount; i++) { var s = {}; for (var c in listToArray(q.columnList)) s[lCase(c)] = q[c][i]; arrayAppend(out, s); } return out;
    }
    boolean function revoke(required numeric id) {
        var r = {}; queryExecute("UPDATE api_keys SET revoked_at=CURRENT_TIMESTAMP WHERE id=:id AND revoked_at IS NULL", {id:arguments.id}, {datasource:variables.datasource, result:"r"});
        return (r.recordCount ?: 0) > 0;
    }
}
