component output=false {
    // Append-only record of user actions. Every write is best-effort: an audit
    // failure is logged but never interrupts the action being audited.
    function init(required string datasource) {
        variables.datasource = arguments.datasource;
        queryExecute("CREATE TABLE IF NOT EXISTS audit_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, actor_user_id BIGINT, actor_username VARCHAR(120), actor_kind VARCHAR(20) NOT NULL DEFAULT 'user', action VARCHAR(80) NOT NULL, target_type VARCHAR(60), target_id VARCHAR(200), outcome VARCHAR(20) NOT NULL DEFAULT 'success', detail_json CLOB, remote_addr VARCHAR(64), correlation_id VARCHAR(24), request_path VARCHAR(500))", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_audit_occurred ON audit_events(occurred_at)", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_events(actor_username)", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_events(action)", {}, {datasource:variables.datasource});
        return this;
    }

    // actor: {id, username} or {} for anonymous (failed logins); detail is any JSON-serialisable struct.
    void function record(required string action, struct actor={}, string targetType="", any targetId="", struct detail={}, string outcome="success", string actorKind="user") {
        try {
            var safeDetail = duplicate(arguments.detail);
            for (var k in ["password","new_password","current_password","confirm_password","secret","token","api_key","client_secret"]) if (structKeyExists(safeDetail, k)) safeDetail[k] = "[redacted]";
            var json = serializeJson(safeDetail);
            if (len(json) > 20000) json = left(json, 19990) & "...""}";
            queryExecute(
                "INSERT INTO audit_events(actor_user_id,actor_username,actor_kind,action,target_type,target_id,outcome,detail_json,remote_addr,correlation_id,request_path) VALUES(:uid,:un,:kind,:act,:tt,:tid,:oc,:dj,:ip,:cid,:path)",
                {
                    uid:{value:val(arguments.actor.id ?: 0), null:!structKeyExists(arguments.actor,"id"), cfsqltype:"cf_sql_bigint"},
                    un:{value:left(arguments.actor.username ?: "", 120), null:!len(arguments.actor.username ?: ""), cfsqltype:"cf_sql_varchar"},
                    kind:{value:left(arguments.actorKind, 20), cfsqltype:"cf_sql_varchar"},
                    act:{value:left(arguments.action, 80), cfsqltype:"cf_sql_varchar"},
                    tt:{value:left(arguments.targetType, 60), null:!len(arguments.targetType), cfsqltype:"cf_sql_varchar"},
                    tid:{value:left(arguments.targetId & "", 200), null:!len(arguments.targetId & ""), cfsqltype:"cf_sql_varchar"},
                    oc:{value:left(arguments.outcome, 20), cfsqltype:"cf_sql_varchar"},
                    dj:{value:json, cfsqltype:"cf_sql_longvarchar"},
                    ip:{value:left(cgi.remote_addr ?: "", 64), cfsqltype:"cf_sql_varchar"},
                    cid:{value:left(request.correlationId ?: "", 24), cfsqltype:"cf_sql_varchar"},
                    path:{value:left(listFirst(cgi.request_uri ?: "", "?"), 500), cfsqltype:"cf_sql_varchar"}
                },
                {datasource:variables.datasource}
            );
        } catch (any e) {
            writeLog(type="error", file="ussi_nexus", text="[" & (request.correlationId ?: "") & "] audit write failed for " & arguments.action & ": " & (e.message ?: ""));
        }
    }

    struct function search(string actor="", string action="", string targetType="", string targetId="", string outcome="", string startDate="", string endDate="", numeric limit=100, numeric offset=0) {
        var where = []; var params = {lim:{value:min(max(arguments.limit,1),1000), cfsqltype:"cf_sql_integer"}, off:{value:max(arguments.offset,0), cfsqltype:"cf_sql_integer"}};
        if (len(trim(arguments.actor))) { params.actor = "%" & trim(arguments.actor) & "%"; arrayAppend(where, "actor_username LIKE :actor"); }
        if (len(trim(arguments.action))) { params.act = "%" & trim(arguments.action) & "%"; arrayAppend(where, "action LIKE :act"); }
        if (len(trim(arguments.targetType))) { params.tt = trim(arguments.targetType); arrayAppend(where, "target_type=:tt"); }
        if (len(trim(arguments.targetId))) { params.tid = trim(arguments.targetId); arrayAppend(where, "target_id=:tid"); }
        if (len(trim(arguments.outcome))) { params.oc = trim(arguments.outcome); arrayAppend(where, "outcome=:oc"); }
        if (isDate(arguments.startDate)) { params.sd = {value:dateFormat(arguments.startDate,"yyyy-mm-dd") & " 00:00:00", cfsqltype:"cf_sql_timestamp"}; arrayAppend(where, "occurred_at>=:sd"); }
        if (isDate(arguments.endDate)) { params.ed = {value:dateFormat(arguments.endDate,"yyyy-mm-dd") & " 23:59:59", cfsqltype:"cf_sql_timestamp"}; arrayAppend(where, "occurred_at<=:ed"); }
        var clause = arrayLen(where) ? " WHERE " & arrayToList(where, " AND ") : "";
        var q = queryExecute("SELECT * FROM audit_events" & clause & " ORDER BY occurred_at DESC, id DESC LIMIT :lim OFFSET :off", params, {datasource:variables.datasource});
        var c = queryExecute("SELECT COUNT(*) c FROM audit_events" & clause, params, {datasource:variables.datasource});
        var rows = [];
        for (var i = 1; i <= q.recordCount; i++) {
            var row = {}; for (var col in listToArray(q.columnList)) row[lCase(col)] = q[col][i];
            try { row.detail = isJson(row.detail_json ?: "") ? deserializeJson(row.detail_json) : {}; } catch (any e) { row.detail = {}; }
            arrayAppend(rows, row);
        }
        return {rows:rows, total:c.c[1], limit:params.lim.value, offset:params.off.value};
    }

    array function actions() {
        var q = queryExecute("SELECT DISTINCT action FROM audit_events ORDER BY action", {}, {datasource:variables.datasource});
        var out = []; for (var r in q) arrayAppend(out, r.action); return out;
    }

    string function toCsv(required array rows) {
        var out = '"Occurred","Actor","Kind","Action","Target type","Target","Outcome","IP","Correlation","Path","Detail"' & chr(13) & chr(10);
        for (var r in arguments.rows) {
            var vals = [dateTimeFormat(r.occurred_at, "yyyy-mm-dd HH:nn:ss"), r.actor_username ?: "", r.actor_kind ?: "", r.action ?: "", r.target_type ?: "", r.target_id ?: "", r.outcome ?: "", r.remote_addr ?: "", r.correlation_id ?: "", r.request_path ?: "", r.detail_json ?: ""];
            var cells = [];
            for (var v in vals) { var t = v & ""; if (len(t) && find(left(t,1), "=+-@" & chr(9) & chr(13))) t = "'" & t; arrayAppend(cells, '"' & replace(t, '"', '""', "all") & '"'); }
            out &= arrayToList(cells, ",") & chr(13) & chr(10);
        }
        return out;
    }
}
