component output=false {
    property name="datasource";

    function init(required string datasource) {
        variables.datasource = arguments.datasource;
        return this;
    }

    void function initSchema() {
        queryExecute("CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(120) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, is_superadmin INT NOT NULL DEFAULT 0, initials VARCHAR(12), theme_preference VARCHAR(20) NOT NULL DEFAULT 'system', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)", {}, {datasource:variables.datasource});
        queryExecute("ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_preference VARCHAR(20) DEFAULT 'system' NOT NULL", {}, {datasource:variables.datasource});
        queryExecute("CREATE TABLE IF NOT EXISTS permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, section VARCHAR(120) NOT NULL, subsection VARCHAR(120), role VARCHAR(40), CONSTRAINT fk_permissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_permissions_user ON permissions(user_id)", {}, {datasource:variables.datasource});
    }

    void function init() {
        initSchema();
        var bootstrapUsername = environmentValue("USSI_NEXUS_BOOTSTRAP_USERNAME");
        if (!len(bootstrapUsername)) bootstrapUsername = "matt.shaw";
        var configuredPassword = environmentValue("USSI_NEXUS_BOOTSTRAP_PASSWORD");
        var bootstrapHash = len(configuredPassword) ? makePassword(configuredPassword) : defaultBootstrapPasswordHash();
        var bootstrapInitials = compareNoCase(bootstrapUsername, "matt.shaw") == 0 ? "MS" : "CI";
        var q = queryExecute("SELECT COUNT(*) AS c FROM users", {}, {datasource:variables.datasource});

        if (q.c[1] == 0) {
            queryExecute(
                "INSERT INTO users(username,password_hash,is_superadmin,initials) VALUES(:u,:p,1,:i)",
                {u:bootstrapUsername,p:bootstrapHash,i:bootstrapInitials},
                {datasource:variables.datasource}
            );
            return;
        }

        // Upgrade only the untouched one-user legacy development database.
        // Any database with additional users or a changed admin password is left alone.
        if (q.c[1] == 1 && !len(configuredPassword)) {
            var legacy = queryExecute("SELECT id,username,password_hash FROM users", {}, {datasource:variables.datasource});
            if (legacy.recordCount == 1 && compareNoCase(legacy.username[1], "admin") == 0 && verifyPassword("admin", legacy.password_hash[1])) {
                queryExecute(
                    "UPDATE users SET username=:u,password_hash=:p,is_superadmin=1,initials=:i WHERE id=:id",
                    {u:bootstrapUsername,p:bootstrapHash,i:bootstrapInitials,id:legacy.id[1]},
                    {datasource:variables.datasource}
                );
            }
        }

        // The designated default account is the portal owner and must retain
        // the highest administration level even in an existing database.
        queryExecute(
            "UPDATE users SET is_superadmin=1 WHERE LOWER(username)=LOWER(:u)",
            {u:"matt.shaw"},
            {datasource:variables.datasource}
        );
    }

    struct function sections() {
        return {
            "invoice-generator": {label:"Invoice Generator", children:{promethean:"Promethean", amc:"AMC", tcl:"TCL", philips:"Philips", config:"Config"}},
            "sms-nonconforming": {label:"SMS NonConforming"},
            "training-tracker": {label:"Training Tracker", roles:["admin","editor","viewer"]},
            "tbd2": {label:"Inventory Management"}
        };
    }

    private string function environmentValue(required string name) {
        var value = createObject("java", "java.lang.System").getenv(arguments.name);
        return isNull(value) ? "" : trim(value & "");
    }

    private string function defaultBootstrapPasswordHash() {
        return "v2$ussi-nexus-dev-bootstrap-v2$ddec87a933a142d14222df8d476906a8f916eab3e664c1fe34bc0c9a1e53a617";
    }

    private string function passwordHashV2(required string password, required string salt) {
        var digest = createObject("java", "java.security.MessageDigest").getInstance("SHA-256");
        var value = charsetDecode(arguments.password & ":" & arguments.salt, "UTF-8");
        for (var i = 1; i <= 120000; i++) value = digest.digest(value);
        return lCase(binaryEncode(value, "hex"));
    }

    private string function passwordHash(required string password, required string salt) {
        return hash(arguments.password & ":" & arguments.salt, "SHA-256", "UTF-8", 120000);
    }

    private string function makePassword(required string password) {
        var salt = lCase(replace(createUUID(), "-", "", "all"));
        return salt & "$" & passwordHash(arguments.password, salt);
    }

    boolean function verifyPassword(required string password, required string stored) {
        if (left(arguments.stored, 3) == "v2$") {
            var modern = listToArray(arguments.stored, "$", true);
            if (arrayLen(modern) != 3) return false;
            return compareNoCase(modern[3], passwordHashV2(arguments.password, modern[2])) == 0;
        }
        if (!find("$", arguments.stored)) return false;
        var bits = listToArray(arguments.stored, "$", true);
        if (arrayLen(bits) != 2) return false;
        return compareNoCase(bits[2], passwordHash(arguments.password, bits[1])) == 0;
    }

    numeric function createUser(required string username, required string password, boolean isSuperadmin=false, string initials="") {
        queryExecute(
            "INSERT INTO users(username,password_hash,is_superadmin,initials) VALUES(:u,:p,:s,:i)",
            {
                u:{value:trim(arguments.username), cfsqltype:"cf_sql_varchar"},
                p:{value:makePassword(arguments.password), cfsqltype:"cf_sql_varchar"},
                s:{value:arguments.isSuperadmin ? 1 : 0, cfsqltype:"cf_sql_integer"},
                i:{value:len(trim(arguments.initials)) ? uCase(trim(arguments.initials)) : javacast("null", ""), null:!len(trim(arguments.initials)), cfsqltype:"cf_sql_varchar"}
            },
            {datasource:variables.datasource}
        );
        var created=queryExecute("SELECT id FROM users WHERE LOWER(username)=LOWER(:u)",{u:trim(arguments.username)},{datasource:variables.datasource});
        return created.recordCount ? val(created.id[1]) : 0;
    }

    struct function authenticate(required string username, required string password) {
        var q = queryExecute("SELECT * FROM users WHERE LOWER(username)=LOWER(:u)", {u:{value:trim(arguments.username), cfsqltype:"cf_sql_varchar"}}, {datasource:variables.datasource});
        if (q.recordCount != 1 || !verifyPassword(arguments.password, q.password_hash[1])) return {};
        return rowToStruct(q, 1);
    }

    struct function getUser(required numeric id) {
        var q = queryExecute("SELECT * FROM users WHERE id=:id", {id:{value:arguments.id,cfsqltype:"cf_sql_bigint"}}, {datasource:variables.datasource});
        return q.recordCount ? rowToStruct(q,1) : {};
    }

    array function listUsers() {
        var q = queryExecute("SELECT * FROM users ORDER BY username", {}, {datasource:variables.datasource});
        return queryToArray(q);
    }

    void function updateUser(required numeric id, string password="", any isSuperadmin=javacast("null",""), any initials=javacast("null","")) {
        if (len(arguments.password)) queryExecute("UPDATE users SET password_hash=:p WHERE id=:id", {p:makePassword(arguments.password),id:arguments.id}, {datasource:variables.datasource});
        if (!isNull(arguments.isSuperadmin)) queryExecute("UPDATE users SET is_superadmin=:s WHERE id=:id", {s:arguments.isSuperadmin?1:0,id:arguments.id}, {datasource:variables.datasource});
        if (!isNull(arguments.initials)) queryExecute("UPDATE users SET initials=:i WHERE id=:id", {i:uCase(trim(arguments.initials)),id:arguments.id}, {datasource:variables.datasource});
    }

    void function updatePreferences(required numeric id, required string themePreference) {
        var theme = lCase(trim(arguments.themePreference));
        if (!listFindNoCase("system,light,dark", theme)) theme = "system";
        queryExecute(
            "UPDATE users SET theme_preference=:t WHERE id=:id",
            {
                t:{value:theme,cfsqltype:"cf_sql_varchar"},
                id:{value:arguments.id,cfsqltype:"cf_sql_bigint"}
            },
            {datasource:variables.datasource}
        );
    }

    boolean function changeOwnPassword(required numeric id, required string currentPassword, required string newPassword) {
        var q = queryExecute("SELECT password_hash FROM users WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource});
        if (q.recordCount != 1 || !verifyPassword(arguments.currentPassword, q.password_hash[1])) return false;
        queryExecute("UPDATE users SET password_hash=:p WHERE id=:id", {p:makePassword(arguments.newPassword),id:arguments.id}, {datasource:variables.datasource});
        return true;
    }

    void function deleteUser(required numeric id) { queryExecute("DELETE FROM users WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource}); }

    boolean function hasAccess(required struct user, required string section, string subsection="") {
        if (!structCount(arguments.user)) return false;
        if (val(arguments.user.is_superadmin ?: 0) == 1) return true;
        var params = {uid:arguments.user.id, sec:arguments.section};
        // Config is privileged and never inherited from the broad Invoice Generator grant.
        if (compareNoCase(arguments.section,"invoice-generator") == 0 && compareNoCase(arguments.subsection,"config") == 0) {
            params.sub = "config";
            var exactConfig = queryExecute("SELECT id FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", params, {datasource:variables.datasource});
            return exactConfig.recordCount > 0;
        }
        var q = queryExecute("SELECT id FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", params, {datasource:variables.datasource});
        if (q.recordCount) return true;
        if (!len(arguments.subsection)) return false;
        params.sub = arguments.subsection;
        q = queryExecute("SELECT id FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", params, {datasource:variables.datasource});
        return q.recordCount > 0;
    }

    string function getRole(required struct user, required string section) {
        if (!structCount(arguments.user)) return "";
        if (val(arguments.user.is_superadmin ?: 0) == 1) return "admin";
        var q = queryExecute("SELECT role FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.user.id,sec:arguments.section}, {datasource:variables.datasource});
        return q.recordCount ? (q.role[1] ?: "") : "";
    }

    array function accessibleChildren(required struct user, required string section) {
        var registry = sections();
        if (!structKeyExists(registry,arguments.section) || !structKeyExists(registry[arguments.section],"children")) return [];
        var children = registry[arguments.section].children;
        if (hasAccess(arguments.user, arguments.section)) {
            var inherited = [];
            for (var child in structKeyArray(children)) if (compareNoCase(child,"config") != 0) arrayAppend(inherited,child);
            if (hasAccess(arguments.user,arguments.section,"config")) arrayAppend(inherited,"config");
            return inherited;
        }
        var q = queryExecute("SELECT subsection FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NOT NULL", {uid:arguments.user.id,sec:arguments.section}, {datasource:variables.datasource});
        var out=[]; for (var item in q) arrayAppend(out,item.subsection); return out;
    }

    struct function getPermissions(required numeric userId) {
        var q = queryExecute("SELECT section,subsection,role FROM permissions WHERE user_id=:id", {id:arguments.userId}, {datasource:variables.datasource});
        var out={}; for (var item in q) out[item.section & "|" & (item.subsection ?: "")] = len(item.role ?: "") ? item.role : "access"; return out;
    }

    void function setPermission(required numeric userId, required string section, string subsection="", string role="access") {
        if (len(arguments.subsection)) {
            queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection}, {datasource:variables.datasource});
            queryExecute("INSERT INTO permissions(user_id,section,subsection,role) VALUES(:uid,:sec,:sub,:role)", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection,role:{value:arguments.role,null:arguments.role=="access"}}, {datasource:variables.datasource});
        } else {
            queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.userId,sec:arguments.section}, {datasource:variables.datasource});
            queryExecute("INSERT INTO permissions(user_id,section,subsection,role) VALUES(:uid,:sec,NULL,:role)", {uid:arguments.userId,sec:arguments.section,role:{value:arguments.role,null:arguments.role=="access"}}, {datasource:variables.datasource});
        }
    }

    void function clearPermission(required numeric userId, required string section, string subsection="") {
        if (len(arguments.subsection)) queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection}, {datasource:variables.datasource});
        else queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.userId,sec:arguments.section}, {datasource:variables.datasource});
    }

    string function initialsFor(required struct user) {
        var explicit = uCase(trim(arguments.user.initials ?: "")); if (len(explicit)) return explicit;
        var username = arguments.user.username ?: ""; var normalized = reReplace(username,"[._-]+"," ","all"); var parts = listToArray(normalized," ");
        if (arrayLen(parts)>=2) return uCase(left(parts[1],1)&left(parts[2],1)); return len(username)>=2 ? uCase(left(username,2)) : "XX";
    }

    private struct function rowToStruct(required query q, required numeric rowNumber) { var s={}; for (var col in listToArray(arguments.q.columnList)) s[lCase(col)]=arguments.q[col][arguments.rowNumber]; return s; }
    private array function queryToArray(required query q) { var a=[]; for (var i=1;i<=arguments.q.recordCount;i++) arrayAppend(a,rowToStruct(arguments.q,i)); return a; }
}
