component output=false {
    // Intranet home ("Nexus hub") content: columns of sections, each either a
    // list of links or a bulletin of rich text. Edited from the browser by users
    // holding the home/editor permission (or superadmins).
    function init(required string datasource) {
        variables.datasource = arguments.datasource;
        variables.targets = ["same", "tab", "window"];
        variables.styles = ["normal", "highlight", "alert"];
        queryExecute("CREATE TABLE IF NOT EXISTS home_sections (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, col INT NOT NULL DEFAULT 1, position INT NOT NULL DEFAULT 0, kind VARCHAR(20) NOT NULL DEFAULT 'links', title VARCHAR(200) NOT NULL, subtitle VARCHAR(500), note_text VARCHAR(500), note_style VARCHAR(20) DEFAULT 'normal', body_html CLOB, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(120))", {}, {datasource:variables.datasource});
        queryExecute("CREATE TABLE IF NOT EXISTS home_links (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, section_id BIGINT NOT NULL, position INT NOT NULL DEFAULT 0, label VARCHAR(200) NOT NULL, url VARCHAR(2000), target VARCHAR(10) NOT NULL DEFAULT 'same', style VARCHAR(20) NOT NULL DEFAULT 'normal', description VARCHAR(500), CONSTRAINT fk_home_links_section FOREIGN KEY(section_id) REFERENCES home_sections(id) ON DELETE CASCADE)", {}, {datasource:variables.datasource});
        queryExecute("CREATE TABLE IF NOT EXISTS home_settings (skey VARCHAR(60) PRIMARY KEY, svalue VARCHAR(500))", {}, {datasource:variables.datasource});
        if (queryExecute("SELECT COUNT(*) c FROM home_sections", {}, {datasource:variables.datasource}).c[1] == 0) seed();
        return this;
    }

    // ---- read -----------------------------------------------------------------
    string function banner() {
        var q = queryExecute("SELECT svalue FROM home_settings WHERE skey='banner'", {}, {datasource:variables.datasource});
        return q.recordCount ? q.svalue[1] : "QUICK LINKS";
    }
    void function setBanner(required string text) {
        var t = left(trim(arguments.text), 120);
        queryExecute("MERGE INTO home_settings(skey,svalue) KEY(skey) VALUES('banner',:v)", {v:len(t) ? t : "QUICK LINKS"}, {datasource:variables.datasource});
    }

    // Columns 1..3, each an array of sections with their links.
    array function columns() {
        var sq = queryExecute("SELECT * FROM home_sections ORDER BY col, position, id", {}, {datasource:variables.datasource});
        var lq = queryExecute("SELECT * FROM home_links ORDER BY section_id, position, id", {}, {datasource:variables.datasource});
        var linksBySection = {};
        for (var i = 1; i <= lq.recordCount; i++) { var l = rowToStruct(lq, i); var key = l.section_id & ""; if (!structKeyExists(linksBySection, key)) linksBySection[key] = []; arrayAppend(linksBySection[key], l); }
        var cols = [[], [], []];
        for (var i = 1; i <= sq.recordCount; i++) { var s = rowToStruct(sq, i); s.links = linksBySection[s.id & ""] ?: []; var c = min(max(val(s.col), 1), 3); arrayAppend(cols[c], s); }
        return cols;
    }
    struct function section(required numeric id) {
        var q = queryExecute("SELECT * FROM home_sections WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource});
        if (!q.recordCount) return {};
        var s = rowToStruct(q, 1);
        var lq = queryExecute("SELECT * FROM home_links WHERE section_id=:id ORDER BY position, id", {id:arguments.id}, {datasource:variables.datasource});
        s.links = []; for (var i = 1; i <= lq.recordCount; i++) arrayAppend(s.links, rowToStruct(lq, i));
        return s;
    }
    struct function link(required numeric id) {
        var q = queryExecute("SELECT * FROM home_links WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource});
        return q.recordCount ? rowToStruct(q, 1) : {};
    }

    // ---- write ----------------------------------------------------------------
    numeric function createSection(required string kind, required string title, string subtitle="", numeric col=1, string actor="") {
        var k = lCase(trim(arguments.kind)); if (!listFind("links,bulletin", k)) fail("Section type must be links or bulletin.");
        var t = trim(arguments.title); if (!len(t) || len(t) > 200) fail("Section title is required (200 characters max).");
        var c = min(max(int(arguments.col), 1), 3);
        var pos = queryExecute("SELECT COALESCE(MAX(position),0)+1 p FROM home_sections WHERE col=:c", {c:c}, {datasource:variables.datasource}).p[1];
        var r = {};
        queryExecute("INSERT INTO home_sections(col,position,kind,title,subtitle,updated_by) VALUES(:c,:p,:k,:t,:s,:u)", {c:c, p:pos, k:k, t:t, s:{value:left(trim(arguments.subtitle),500), null:!len(trim(arguments.subtitle))}, u:left(arguments.actor,120)}, {datasource:variables.datasource, result:"r"});
        return structKeyExists(r, "generatedKey") ? val(r.generatedKey) : val(queryExecute("SELECT MAX(id) id FROM home_sections", {}, {datasource:variables.datasource}).id[1]);
    }
    void function updateSection(required numeric id, required string title, string subtitle="", string noteText="", string noteStyle="normal", string bodyHtml="", string actor="") {
        var t = trim(arguments.title); if (!len(t) || len(t) > 200) fail("Section title is required (200 characters max).");
        var ns = lCase(trim(arguments.noteStyle)); if (!arrayFindNoCase(variables.styles, ns)) ns = "normal";
        if (len(trim(arguments.noteText)) > 500) fail("The note is limited to 500 characters.");
        var body = this.sanitizeBulletinHtml(arguments.bodyHtml);
        if (len(body) > 60000) fail("The bulletin is too long (60,000 characters max).");
        queryExecute("UPDATE home_sections SET title=:t, subtitle=:s, note_text=:n, note_style=:ns, body_html=:b, updated_at=CURRENT_TIMESTAMP, updated_by=:u WHERE id=:id",
            {t:t, s:{value:left(trim(arguments.subtitle),500), null:!len(trim(arguments.subtitle))}, n:{value:trim(arguments.noteText), null:!len(trim(arguments.noteText))}, ns:ns, b:{value:body, cfsqltype:"cf_sql_longvarchar", null:!len(body)}, u:left(arguments.actor,120), id:arguments.id}, {datasource:variables.datasource});
    }
    boolean function deleteSection(required numeric id) {
        var r = {}; queryExecute("DELETE FROM home_sections WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource, result:"r"}); return (r.recordCount ?: 0) > 0;
    }
    void function moveSection(required numeric id, required string direction) {
        var s = section(arguments.id); if (!structCount(s)) return;
        if (listFind("left,right", arguments.direction)) {
            var newCol = min(max(val(s.col) + (arguments.direction == "left" ? -1 : 1), 1), 3);
            var pos = queryExecute("SELECT COALESCE(MAX(position),0)+1 p FROM home_sections WHERE col=:c", {c:newCol}, {datasource:variables.datasource}).p[1];
            queryExecute("UPDATE home_sections SET col=:c, position=:p WHERE id=:id", {c:newCol, p:pos, id:arguments.id}, {datasource:variables.datasource});
            renumber(); return;
        }
        renumber();
        var q = queryExecute("SELECT id FROM home_sections WHERE col=:c ORDER BY position, id", {c:s.col}, {datasource:variables.datasource});
        var ids = []; for (var row in q) arrayAppend(ids, row.id);
        var idx = arrayFind(ids, arguments.id); if (!idx) return;
        var swap = arguments.direction == "up" ? idx - 1 : idx + 1; if (swap < 1 || swap > arrayLen(ids)) return;
        var tmp = ids[idx]; ids[idx] = ids[swap]; ids[swap] = tmp;
        for (var i = 1; i <= arrayLen(ids); i++) queryExecute("UPDATE home_sections SET position=:p WHERE id=:id", {p:i, id:ids[i]}, {datasource:variables.datasource});
    }
    private void function renumber() {
        for (var c = 1; c <= 3; c++) { var q = queryExecute("SELECT id FROM home_sections WHERE col=:c ORDER BY position, id", {c:c}, {datasource:variables.datasource}); var i = 0; for (var row in q) { i++; queryExecute("UPDATE home_sections SET position=:p WHERE id=:id", {p:i, id:row.id}, {datasource:variables.datasource}); } }
    }

    numeric function addLink(required numeric sectionId, required string label, string href="", string target="same", string style="normal", string description="") {
        var s = section(arguments.sectionId); if (!structCount(s)) fail("Section not found."); if (s.kind != "links") fail("Links can only be added to a links section.");
        var clean = cleanLink(arguments.label, arguments.href, arguments.target, arguments.style, arguments.description);
        var pos = queryExecute("SELECT COALESCE(MAX(position),0)+1 p FROM home_links WHERE section_id=:s", {s:arguments.sectionId}, {datasource:variables.datasource}).p[1];
        var r = {};
        queryExecute("INSERT INTO home_links(section_id,position,label,url,target,style,description) VALUES(:s,:p,:l,:u,:t,:st,:d)", {s:arguments.sectionId, p:pos, l:clean.label, u:{value:clean.url, null:!len(clean.url)}, t:clean.target, st:clean.style, d:{value:clean.description, null:!len(clean.description)}}, {datasource:variables.datasource, result:"r"});
        queryExecute("UPDATE home_sections SET updated_at=CURRENT_TIMESTAMP WHERE id=:id", {id:arguments.sectionId}, {datasource:variables.datasource});
        return structKeyExists(r, "generatedKey") ? val(r.generatedKey) : val(queryExecute("SELECT MAX(id) id FROM home_links", {}, {datasource:variables.datasource}).id[1]);
    }
    void function updateLink(required numeric id, required string label, string href="", string target="same", string style="normal", string description="") {
        var clean = cleanLink(arguments.label, arguments.href, arguments.target, arguments.style, arguments.description);
        queryExecute("UPDATE home_links SET label=:l, url=:u, target=:t, style=:st, description=:d WHERE id=:id", {l:clean.label, u:{value:clean.url, null:!len(clean.url)}, t:clean.target, st:clean.style, d:{value:clean.description, null:!len(clean.description)}, id:arguments.id}, {datasource:variables.datasource});
    }
    boolean function deleteLink(required numeric id) {
        var r = {}; queryExecute("DELETE FROM home_links WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource, result:"r"}); return (r.recordCount ?: 0) > 0;
    }
    void function moveLink(required numeric id, required string direction) {
        var l = link(arguments.id); if (!structCount(l)) return;
        var q = queryExecute("SELECT id FROM home_links WHERE section_id=:s ORDER BY position, id", {s:l.section_id}, {datasource:variables.datasource});
        var ids = []; for (var row in q) arrayAppend(ids, row.id);
        var idx = arrayFind(ids, arguments.id); if (!idx) return;
        var swap = arguments.direction == "up" ? idx - 1 : idx + 1; if (swap < 1 || swap > arrayLen(ids)) return;
        var tmp = ids[idx]; ids[idx] = ids[swap]; ids[swap] = tmp;
        for (var i = 1; i <= arrayLen(ids); i++) queryExecute("UPDATE home_links SET position=:p WHERE id=:id", {p:i, id:ids[i]}, {datasource:variables.datasource});
    }

    private struct function cleanLink(required string label, required string href, required string target, required string style, required string description) {
        var l = trim(arguments.label); if (!len(l) || len(l) > 200) fail("Link text is required (200 characters max).");
        var u = this.validLinkAddress(arguments.href); if (len(trim(arguments.href)) && !len(u)) fail("Link address must start with http://, https://, mailto:, tel: or / (got '" & left(trim(arguments.href), 60) & "').");
        var t = lCase(trim(arguments.target)); if (!arrayFindNoCase(variables.targets, t)) t = "same";
        var st = lCase(trim(arguments.style)); if (!arrayFindNoCase(variables.styles, st)) st = "normal";
        if (len(trim(arguments.description)) > 500) fail("Link description is limited to 500 characters.");
        return {label:l, url:u, target:t, style:st, description:trim(arguments.description)};
    }
    // Accepts absolute http(s), mailto:, tel: and site-relative paths; rejects javascript:, data: and protocol-relative.
    string function validLinkAddress(required string href) {
        var u = trim(arguments.href); if (!len(u) || len(u) > 2000) return "";
        if (find(" ", u) || find(chr(9), u) || find(chr(10), u) || find(chr(13), u)) return "";
        var lower = lCase(u);
        if (left(lower, 7) == "http://" && len(u) > 7) return u;
        if (left(lower, 8) == "https://" && len(u) > 8) return u;
        if (left(lower, 7) == "mailto:" && len(u) > 7) return u;
        if (left(lower, 4) == "tel:" && len(u) > 4) return u;
        if (u == "/") return u;
        if (left(u, 1) == "/" && left(u, 2) != "//" && left(u, 2) != "/\") return u;
        return "";
    }

    // ---- sanitizer -------------------------------------------------------------
    // NOTE: method names here deliberately avoid Lucee built-ins. An unscoped call
    // to a method that shares a name with a BIF (e.g. sanitizeHTML) resolves to the
    // BIF, which silently replaced this sanitizer until the names were changed.
    // The text is HTML-escaped, then scanned tag by tag (no regex, so behaviour
    // does not depend on the engine's regex flavour). Only the tags below are
    // restored; <a> keeps a validated href plus an optional new-tab target;
    // everything else stays as visible, escaped text.
    string function escapeHubText(required string text) {
        return replace(replace(replace(replace(replace(arguments.text, "&", "&amp;", "all"), "<", "&lt;", "all"), ">", "&gt;", "all"), '"', "&quot;", "all"), "'", "&##39;", "all");
    }
    string function sanitizeBulletinHtml(required string html) {
        var allowed = {p:1, br:1, strong:1, b:1, em:1, i:1, u:1, ul:1, ol:1, li:1, h3:1, h4:1, blockquote:1, mark:1, s:1};
        var aliases = {b:"strong", i:"em", h4:"h3"};
        var enc = this.escapeHubText(arguments.html);
        var parts = listToArray(enc, "&lt;", true, true);
        if (!arrayLen(parts)) return "";
        var out = parts[1];
        var anchors = []; // true = emitted, false = dropped (its closer is dropped too)
        for (var i = 2; i <= arrayLen(parts); i++) {
            var chunk = parts[i];
            var close = find("&gt;", chunk);
            if (!close) { out &= "&lt;" & chunk; continue; }
            var body = trim(left(chunk, close - 1)); var rest = mid(chunk, close + 4, len(chunk));
            var closing = left(body, 1) == "/"; if (closing) body = trim(mid(body, 2, len(body)));
            var nameEnd = reFind("[^A-Za-z0-9]", body); var name = lCase(nameEnd ? left(body, nameEnd - 1) : body);
            var attrs = nameEnd ? mid(body, nameEnd, len(body)) : "";
            if (name == "a") {
                if (closing) { if (arrayLen(anchors)) { var wasEmitted = anchors[arrayLen(anchors)]; arrayDeleteAt(anchors, arrayLen(anchors)); if (wasEmitted) out &= "</a>"; } }
                else {
                    var href = this.validLinkAddress(replace(hubAttrValue(attrs, "href"), "&amp;", "&", "all"));
                    var newTab = lCase(hubAttrValue(attrs, "target")) == "_blank";
                    if (len(href)) { out &= '<a href="' & escapeHubText(href) & '"' & (newTab ? ' target="_blank" rel="noopener noreferrer"' : '') & '>'; arrayAppend(anchors, true); }
                    else arrayAppend(anchors, false);
                }
                out &= rest; continue;
            }
            if (structKeyExists(allowed, name)) {
                var tag = aliases[name] ?: name;
                if (name == "br") out &= "<br>";
                else out &= (closing ? "</" : "<") & tag & ">";
                out &= rest; continue;
            }
            out &= "&lt;" & chunk; // unknown tag stays visible as text
        }
        return trim(out);
    }
    // Reads name=&quot;value&quot; from an escaped attribute string.
    private string function hubAttrValue(required string attrs, required string name) {
        var key = lCase(arguments.name) & "=&quot;";
        var at = findNoCase(key, arguments.attrs); if (!at) return "";
        var from = at + len(key); var to = find("&quot;", arguments.attrs, from); if (!to) return "";
        return mid(arguments.attrs, from, to - from);
    }

    private void function fail(required string message) { throw(type="Logicore.Validation", message=arguments.message); }
    private struct function rowToStruct(required query q, required numeric row) { var s = {}; for (var c in listToArray(arguments.q.columnList)) s[lCase(c)] = arguments.q[c][arguments.row]; return s; }

    // Starting content mirrors the legacy intranet Quick Links page; addresses are
    // left blank so an editor fills them in from the edit screen.
    private void function seed() {
        var defs = [
            {col:1, kind:"links", title:"Employees:", links:["Password Reset", "Suggestion Box"]},
            {col:1, kind:"links", title:"NGERP:", links:[{l:"Remote NGERP access", style:"highlight"}]},
            {col:1, kind:"links", title:"Remote Worker Resources:", links:["Outlook Link", "RDP Reference (Remote Desktop)", "USSI Global VPN Access Instructions", "Zoom SSO Instructions"]},
            {col:1, kind:"links", title:"Remote Manager Resources:", subtitle:"For USSI Global manager Star2Star settings:", links:["Find Me Follow Me and Multi-Queue Monitor (Star2Star)"]},
            {col:1, kind:"links", title:"Tech Support:", links:["Knowledge Base Doc Add Request", "Knowledge Base Doc Queue", "Virtual Office Manual", "Tech Mobile Manual"]},
            {col:1, kind:"links", title:"Training:", subtitle:"Training now available on your HRO page", links:["Quick Start Guide for Intranet", "Forklift Training Video", "LMS"]},
            {col:2, kind:"links", title:"Information Systems:", note:"All USSI Employees can create IS Tickets", noteStyle:"alert", links:["Create IS Ticket"]},
            {col:2, kind:"links", title:"Field Services:", links:["FE/Technician Search"]},
            {col:2, kind:"links", title:"International Dial Plan:", links:["International Dial Plan"]},
            {col:2, kind:"links", title:"Extensions for Employees/Groups:", links:["Employee Phone Directory", "Group Extension Directory", "Group Email Directory"]},
            {col:2, kind:"links", title:"Policies & Procedures:", subtitle:"(Use your network logon to access. IE: ""firstname.lastname"", then your regular password...)", links:["USSI Global Security Guidelines"]},
            {col:3, kind:"bulletin", title:"USSI Spam Filter:", body:"<p>USSIGlobal Team, the new Spam Filter location is <a href=""https://datamg.ussi.global/quarantine"" target=""_blank"">https://datamg.ussi.global/quarantine</a>. You can use this to allow email that has been flagged as spam to be delivered if it is a legitimate email.</p><p>A log in screen will pop up; please use your @USSIGlobal email address and the password you use to log into your computer with.</p><p><mark>If you are having issues with delayed email, you can also click on ""Whitelist"" in the left pane and add the senders email address to permanently allow from that sender.</mark></p><p>You can select ""Blacklist"" and ""Delete"" if you do not want email from that sender.</p>"}
        ];
        for (var d in defs) {
            var id = createSection(d.kind, d.title, d.subtitle ?: "", d.col, "seed");
            updateSection(id, d.title, d.subtitle ?: "", d.note ?: "", d.noteStyle ?: "normal", d.body ?: "", "seed");
            for (var l in d.links ?: []) { if (isSimpleValue(l)) addLink(id, l); else addLink(id, l.l, l.href ?: "", l.t ?: "same", l.style ?: "normal"); }
        }
        setBanner("QUICK LINKS");
    }
}
