component output=false {
    function init(required string datasource, required string rootPath, required any excelService){
        variables.datasource=arguments.datasource;
        variables.rootPath=arguments.rootPath;
        variables.excel=arguments.excelService;
        variables.uploadPath=arguments.rootPath&"data/training_signoffs/";
        variables.outputPath=arguments.rootPath&"outputs/";
        if(!directoryExists(variables.uploadPath))directoryCreate(variables.uploadPath,true);
        bootstrap();
        return this;
    }

    void function bootstrap(){
        var sql=[
            "CREATE TABLE IF NOT EXISTS training_weeks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, week_number INT NOT NULL, title VARCHAR(500) NOT NULL, start_date DATE, notes CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS training_topics (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, week_id BIGINT NOT NULL, title VARCHAR(500) NOT NULL, lesson_plan CLOB, key_points CLOB, sort_order INT DEFAULT 0, CONSTRAINT fk_topic_week FOREIGN KEY(week_id) REFERENCES training_weeks(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS training_videos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, topic_id BIGINT NOT NULL, title VARCHAR(500), url VARCHAR(2000) NOT NULL, CONSTRAINT fk_video_topic FOREIGN KEY(topic_id) REFERENCES training_topics(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS training_people (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(500) NOT NULL, email VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS training_sessions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, week_id BIGINT NOT NULL, trainer_name VARCHAR(500) NOT NULL DEFAULT 'Unassigned', session_date DATE, location VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_session_week FOREIGN KEY(week_id) REFERENCES training_weeks(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS training_attendance (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT NOT NULL, person_id BIGINT NOT NULL, attended INT DEFAULT 0, signature CLOB, signed_at TIMESTAMP, CONSTRAINT uq_training_att UNIQUE(session_id,person_id), CONSTRAINT fk_att_session FOREIGN KEY(session_id) REFERENCES training_sessions(id) ON DELETE CASCADE, CONSTRAINT fk_att_person FOREIGN KEY(person_id) REFERENCES training_people(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS training_content (key_name VARCHAR(255) PRIMARY KEY, value_text CLOB)",
            "CREATE TABLE IF NOT EXISTS training_theme (key_name VARCHAR(255) PRIMARY KEY, value_text VARCHAR(255))",
            "CREATE TABLE IF NOT EXISTS training_signoff_uploads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT NOT NULL UNIQUE, filename VARCHAR(500) NOT NULL, original_filename VARCHAR(500), content_type VARCHAR(255), uploaded_by VARCHAR(120), uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_sign_session FOREIGN KEY(session_id) REFERENCES training_sessions(id) ON DELETE CASCADE)"
        ];
        for(var stmt in sql)queryExecute(stmt,{}, {datasource:variables.datasource});
    }

    array function weeks(){
        var q=queryExecute("SELECT w.*, (SELECT COUNT(*) FROM training_topics t WHERE t.week_id=w.id) topic_count, (SELECT COUNT(*) FROM training_sessions s WHERE s.week_id=w.id) session_count, (SELECT COUNT(*) FROM training_attendance a JOIN training_sessions s2 ON s2.id=a.session_id WHERE s2.week_id=w.id AND a.attended=1) attended_count, (SELECT COUNT(*) FROM training_attendance a JOIN training_sessions s3 ON s3.id=a.session_id WHERE s3.week_id=w.id AND a.attended=1 AND a.signature IS NOT NULL) signed_count FROM training_weeks w ORDER BY COALESCE(w.start_date,DATE '1900-01-01') DESC,w.title ASC",{}, {datasource:variables.datasource});
        return toArray(q);
    }
    struct function week(required numeric id){
        var q=queryExecute("SELECT * FROM training_weeks WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});if(!q.recordCount)return{};
        var w=row(q,1);w.topics=topics(arguments.id);w.sessions=sessions(arguments.id);var p=weekProgress(arguments.id);w.attended=p.attended;w.signed=p.signed;return w;
    }
    numeric function createWeek(string title="",string startDate="",string notes=""){
        // week_number is allocated as MAX+1, so allocation and insert are serialized
        // (this application runs as a single instance against the H2 file store).
        var newId=0;
        lock name="ussi-training-week-number" type="exclusive" timeout="10"{
            var n=queryExecute("SELECT COALESCE(MAX(week_number),0)+1 n FROM training_weeks",{}, {datasource:variables.datasource}).n[1];var title=len(trim(arguments.title))?trim(arguments.title):"Week "&n;
            var r={};queryExecute("INSERT INTO training_weeks(week_number,title,start_date,notes) VALUES(:n,:t,:d,:notes)",{n:n,t:title,d:{value:arguments.startDate,null:!len(arguments.startDate)},notes:arguments.notes},{datasource:variables.datasource,result:"r"});
            newId=insertedId(r,"training_weeks");
        }
        return newId;
    }
    void function updateWeek(required numeric id,required string title,string startDate="",string notes=""){queryExecute("UPDATE training_weeks SET title=:t,start_date=:d,notes=:n WHERE id=:id",{t:trim(arguments.title),d:{value:arguments.startDate,null:!len(arguments.startDate)},n:arguments.notes,id:arguments.id},{datasource:variables.datasource});}
    void function deleteWeek(required numeric id){for(var s in sessions(arguments.id))removeSignoff(s.id);queryExecute("DELETE FROM training_weeks WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});}

    array function topics(required numeric weekId){var a=toArray(queryExecute("SELECT * FROM training_topics WHERE week_id=:id ORDER BY sort_order,id",{id:arguments.weekId},{datasource:variables.datasource}));for(var t in a)t.videos=videos(t.id);return a;}
    struct function topic(required numeric id){var q=queryExecute("SELECT * FROM training_topics WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});return q.recordCount?row(q,1):{};}
    numeric function createTopic(required numeric weekId,string title="",string lessonPlan="",string keyPoints=""){
        var sort=queryExecute("SELECT COALESCE(MAX(sort_order),0)+1 n FROM training_topics WHERE week_id=:id",{id:arguments.weekId},{datasource:variables.datasource}).n[1];var title=len(trim(arguments.title))?trim(arguments.title):"Untitled topic";
        var r={};queryExecute("INSERT INTO training_topics(week_id,title,lesson_plan,key_points,sort_order) VALUES(:w,:t,:l,:k,:s)",{w:arguments.weekId,t:title,l:arguments.lessonPlan,k:arguments.keyPoints,s:sort},{datasource:variables.datasource,result:"r"});return insertedId(r,"training_topics");
    }
    void function updateTopic(required numeric id,string title="",string lessonPlan="",string keyPoints=""){queryExecute("UPDATE training_topics SET title=:t,lesson_plan=:l,key_points=:k WHERE id=:id",{t:len(trim(arguments.title))?trim(arguments.title):"Untitled topic",l:arguments.lessonPlan,k:arguments.keyPoints,id:arguments.id},{datasource:variables.datasource});}
    void function deleteTopic(required numeric id){queryExecute("DELETE FROM training_topics WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});}
    array function videos(required numeric topicId){return toArray(queryExecute("SELECT * FROM training_videos WHERE topic_id=:id ORDER BY id",{id:arguments.topicId},{datasource:variables.datasource}));}
    numeric function addVideo(required numeric topicId,string title="",required string url){var cleanUrl=trim(arguments.url);if(!reFindNoCase("^https?://",cleanUrl))throw(type="Logicore.Validation",message="Video links must begin with http:// or https://.");var r={};queryExecute("INSERT INTO training_videos(topic_id,title,url) VALUES(:id,:t,:u)",{id:arguments.topicId,t:len(trim(arguments.title))?trim(arguments.title):cleanUrl,u:cleanUrl},{datasource:variables.datasource,result:"r"});return insertedId(r,"training_videos");}
    struct function video(required numeric id){var q=queryExecute("SELECT v.*,t.week_id FROM training_videos v JOIN training_topics t ON t.id=v.topic_id WHERE v.id=:id",{id:arguments.id},{datasource:variables.datasource});return q.recordCount?row(q,1):{};}
    void function deleteVideo(required numeric id){queryExecute("DELETE FROM training_videos WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});}

    array function people(){return toArray(queryExecute("SELECT * FROM training_people ORDER BY name",{}, {datasource:variables.datasource}));}
    numeric function addPerson(required string name,string email=""){if(!len(trim(arguments.name)))return 0;var r={};queryExecute("INSERT INTO training_people(name,email) VALUES(:n,:e)",{n:trim(arguments.name),e:trim(arguments.email)},{datasource:variables.datasource,result:"r"});var id=insertedId(r,"training_people");for(var s in allSessions())seedAttendance(s.id);return id;}
    void function updatePerson(required numeric id,required string name,string email=""){queryExecute("UPDATE training_people SET name=:n,email=:e WHERE id=:id",{n:arguments.name,e:arguments.email,id:arguments.id},{datasource:variables.datasource});}
    void function deletePerson(required numeric id){queryExecute("DELETE FROM training_people WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});}

    array function sessions(required numeric weekId){var q=queryExecute("SELECT s.*, (SELECT COUNT(*) FROM training_attendance a WHERE a.session_id=s.id AND a.attended=1) attended_count, (SELECT COUNT(*) FROM training_attendance a WHERE a.session_id=s.id AND a.attended=1 AND a.signature IS NOT NULL) signed_count FROM training_sessions s WHERE s.week_id=:id ORDER BY s.session_date,s.id",{id:arguments.weekId},{datasource:variables.datasource});var a=toArray(q);for(var s in a)s.upload=signoffUpload(s.id);return a;}
    array function allSessions(){return toArray(queryExecute("SELECT * FROM training_sessions ORDER BY week_id,session_date,id",{}, {datasource:variables.datasource}));}
    struct function session(required numeric id){var q=queryExecute("SELECT s.*,w.week_number,w.title week_title,w.start_date week_start_date FROM training_sessions s JOIN training_weeks w ON w.id=s.week_id WHERE s.id=:id",{id:arguments.id},{datasource:variables.datasource});if(!q.recordCount)return{};var s=row(q,1);s.attendance=attendance(arguments.id);s.upload=signoffUpload(arguments.id);return s;}
    numeric function createSession(required numeric weekId,string trainerName="",string sessionDate="",string location=""){var r={};queryExecute("INSERT INTO training_sessions(week_id,trainer_name,session_date,location) VALUES(:w,:t,:d,:l)",{w:arguments.weekId,t:len(trim(arguments.trainerName))?trim(arguments.trainerName):"Unassigned",d:{value:arguments.sessionDate,null:!len(arguments.sessionDate)},l:{value:trim(arguments.location),null:!len(trim(arguments.location))}},{datasource:variables.datasource,result:"r"});var id=insertedId(r,"training_sessions");seedAttendance(id);return id;}
    void function updateSession(required numeric id,string trainerName="",string sessionDate="",string location=""){queryExecute("UPDATE training_sessions SET trainer_name=:t,session_date=:d,location=:l WHERE id=:id",{t:len(trim(arguments.trainerName))?trim(arguments.trainerName):"Unassigned",d:{value:arguments.sessionDate,null:!len(arguments.sessionDate)},l:{value:trim(arguments.location),null:!len(trim(arguments.location))},id:arguments.id},{datasource:variables.datasource});}
    void function deleteSession(required numeric id){removeSignoff(arguments.id);queryExecute("DELETE FROM training_sessions WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});}

    void function seedAttendance(required numeric sessionId){queryExecute("INSERT INTO training_attendance(session_id,person_id,attended) SELECT :sid,p.id,0 FROM training_people p WHERE NOT EXISTS(SELECT 1 FROM training_attendance a WHERE a.session_id=:sid2 AND a.person_id=p.id)",{sid:arguments.sessionId,sid2:arguments.sessionId},{datasource:variables.datasource});}
    array function attendance(required numeric sessionId){seedAttendance(arguments.sessionId);return toArray(queryExecute("SELECT a.*,p.name,p.email FROM training_attendance a JOIN training_people p ON p.id=a.person_id WHERE a.session_id=:id ORDER BY p.name",{id:arguments.sessionId},{datasource:variables.datasource}));}
    void function setAttendance(required numeric sessionId,required numeric personId,required boolean attended){seedAttendance(arguments.sessionId);queryExecute("UPDATE training_attendance SET attended=:a,signature=CASE WHEN :a2=0 THEN NULL ELSE signature END,signed_at=CASE WHEN :a3=0 THEN NULL ELSE signed_at END WHERE session_id=:s AND person_id=:p",{a:arguments.attended?1:0,a2:arguments.attended?1:0,a3:arguments.attended?1:0,s:arguments.sessionId,p:arguments.personId},{datasource:variables.datasource});}
    void function toggleAttendance(required numeric sessionId,required numeric personId,required boolean attended){setAttendance(arguments.sessionId,arguments.personId,arguments.attended);}
    void function sign(required numeric sessionId,required numeric personId,required string signature){seedAttendance(arguments.sessionId);queryExecute("UPDATE training_attendance SET attended=1,signature=:sig,signed_at=CURRENT_TIMESTAMP WHERE session_id=:s AND person_id=:p",{sig:arguments.signature,s:arguments.sessionId,p:arguments.personId},{datasource:variables.datasource});}
    struct function weekProgress(required numeric weekId){var q=queryExecute("SELECT COUNT(DISTINCT a.person_id) attended,COUNT(DISTINCT CASE WHEN a.signature IS NOT NULL THEN a.person_id END) signed FROM training_attendance a JOIN training_sessions s ON s.id=a.session_id WHERE s.week_id=:id AND a.attended=1",{id:arguments.weekId},{datasource:variables.datasource});return{attended:q.attended[1],signed:q.signed[1]};}
    struct function sessionProgress(required numeric sessionId){var q=queryExecute("SELECT COUNT(*) attended,COUNT(CASE WHEN signature IS NOT NULL THEN 1 END) signed FROM training_attendance WHERE session_id=:id AND attended=1",{id:arguments.sessionId},{datasource:variables.datasource});return{attended:q.attended[1],signed:q.signed[1]};}

    struct function signoffUpload(required numeric sessionId){var q=queryExecute("SELECT * FROM training_signoff_uploads WHERE session_id=:id",{id:arguments.sessionId},{datasource:variables.datasource});return q.recordCount?row(q,1):{};}
    struct function saveSignoff(required numeric sessionId,required string sourcePath,required string originalFilename,required string contentType,required string username){
        var ext=lCase(listLast(arguments.originalFilename,"."));if(!listFindNoCase("pdf,png,jpg,jpeg,gif,webp,heic",ext))throw(type="Logicore.Training",message="That file type isn't supported. Use PDF, PNG, JPG, GIF, WEBP, or HEIC.");
        var contentTypes={pdf:"application/pdf",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",gif:"image/gif",webp:"image/webp",heic:"image/heic"};var safeContentType=contentTypes[ext];
        var old=signoffUpload(arguments.sessionId);if(structCount(old)&&fileExists(variables.uploadPath&old.filename))fileDelete(variables.uploadPath&old.filename);
        var stored="session_"&arguments.sessionId&"_"&left(replace(createUUID(),"-","","all"),16)&"."&ext;fileCopy(arguments.sourcePath,variables.uploadPath&stored);
        if(structCount(old))queryExecute("UPDATE training_signoff_uploads SET filename=:f,original_filename=:o,content_type=:ct,uploaded_by=:u,uploaded_at=CURRENT_TIMESTAMP WHERE session_id=:s",{f:stored,o:safeName(arguments.originalFilename),ct:safeContentType,u:arguments.username,s:arguments.sessionId},{datasource:variables.datasource});
        else queryExecute("INSERT INTO training_signoff_uploads(session_id,filename,original_filename,content_type,uploaded_by) VALUES(:s,:f,:o,:ct,:u)",{s:arguments.sessionId,f:stored,o:safeName(arguments.originalFilename),ct:safeContentType,u:arguments.username},{datasource:variables.datasource});
        return signoffUpload(arguments.sessionId);
    }
    void function removeSignoff(required numeric sessionId){var old=signoffUpload(arguments.sessionId);if(structCount(old)&&fileExists(variables.uploadPath&old.filename))try{fileDelete(variables.uploadPath&old.filename);}catch(any ignored){}queryExecute("DELETE FROM training_signoff_uploads WHERE session_id=:id",{id:arguments.sessionId},{datasource:variables.datasource});}
    string function signoffPath(required numeric sessionId){var u=signoffUpload(arguments.sessionId);if(!structCount(u))return"";var p=variables.uploadPath&u.filename;return fileExists(p)?p:"";}

    struct function report(){var stats={weeks:scalar("SELECT COUNT(*) FROM training_weeks"),people:scalar("SELECT COUNT(*) FROM training_people"),sessions:scalar("SELECT COUNT(*) FROM training_sessions"),attended:scalar("SELECT COUNT(*) FROM training_attendance WHERE attended=1"),signed:scalar("SELECT COUNT(*) FROM training_attendance WHERE attended=1 AND signature IS NOT NULL")};stats.weeks_detail=weeks();return stats;}
    struct function dateRange(string startDate="",string endDate=""){
        var q=queryExecute("SELECT MIN(start_date) lo,MAX(start_date) hi FROM training_weeks WHERE start_date IS NOT NULL",{}, {datasource:variables.datasource});
        if(isNull(q.lo[1]))return{ok:false,error:"No dated training courses exist yet."};
        var lo=dateFormat(q.lo[1],"yyyy-mm-dd");var hi=dateFormat(q.hi[1],"yyyy-mm-dd");
        if(len(trim(arguments.startDate))){try{lo=dateFormat(parseDateTime(arguments.startDate),"yyyy-mm-dd");}catch(any ignored){return{ok:false,error:"Invalid start date."};}}
        if(len(trim(arguments.endDate))){try{hi=dateFormat(parseDateTime(arguments.endDate),"yyyy-mm-dd");}catch(any ignored){return{ok:false,error:"Invalid end date."};}}
        if(parseDateTime(lo)>parseDateTime(hi)){var t=lo;lo=hi;hi=t;}
        return{ok:true,lo:lo,hi:hi};
    }
    array function coursesInDateRange(required string lo,required string hi){
        var params={lo:{value:arguments.lo,cfsqltype:"cf_sql_date"},hi:{value:arguments.hi,cfsqltype:"cf_sql_date"}};
        return toArray(queryExecute("SELECT * FROM training_weeks WHERE start_date BETWEEN :lo AND :hi ORDER BY start_date,title,id",params,{datasource:variables.datasource}));
    }
    string function buildAttendanceMatrix(required string lo,required string hi){
        var courses=coursesInDateRange(arguments.lo,arguments.hi);var ppl=people();var marks={};var params={lo:{value:arguments.lo,cfsqltype:"cf_sql_date"},hi:{value:arguments.hi,cfsqltype:"cf_sql_date"}};
        var q=queryExecute("SELECT s.week_id,a.person_id FROM training_attendance a JOIN training_sessions s ON s.id=a.session_id JOIN training_weeks w ON w.id=s.week_id WHERE a.attended=1 AND w.start_date BETWEEN :lo AND :hi",params,{datasource:variables.datasource});
        for(var x in q)marks[x.week_id&"|"&x.person_id]=true;
        var headers=["Name"];for(var course in courses)arrayAppend(headers,dateFormat(course.start_date,"yyyy-mm-dd")&" - "&course.title);
        var rows=[];for(var person in ppl){var record={Name:person.name};for(var course in courses){var label=dateFormat(course.start_date,"yyyy-mm-dd")&" - "&course.title;record[label]=structKeyExists(marks,course.id&"|"&person.id)?"X":"";}arrayAppend(rows,record);}
        var name="Attendance "&arguments.lo&" to "&arguments.hi&".xlsx";variables.excel.writeWorkbook(variables.outputPath&name,[{name:"Attendance",headers:headers,rows:rows}]);return name;
    }
    string function buildSignoffZip(required string lo,required string hi){
        var courses=coursesInDateRange(arguments.lo,arguments.hi);var files=[];
        for(var course in courses){for(var s in sessions(course.id)){var u=signoffUpload(s.id);if(structCount(u)){var p=variables.uploadPath&u.filename;if(fileExists(p))arrayAppend(files,{path:p,name:dateFormat(course.start_date,"yyyy-mm-dd")&" - "&safeName(course.title)&(s.trainer_name!="Unassigned"?" - "&safeName(s.trainer_name):"")&"."&lCase(listLast(u.filename,"."))});}}}
        if(!arrayLen(files))return"";var filename="Signoff Sheets "&arguments.lo&" to "&arguments.hi&".zip";var fos=createObject("java","java.io.FileOutputStream").init(variables.outputPath&filename);var zos=createObject("java","java.util.zip.ZipOutputStream").init(fos);try{for(var f in files){var entry=createObject("java","java.util.zip.ZipEntry").init(f.name);zos.putNextEntry(entry);var bytes=fileReadBinary(f.path);zos.write(bytes,0,len(bytes));zos.closeEntry();}}finally{zos.close();fos.close();}return filename;
    }

    struct function content(){var out=contentDefaults();var q=queryExecute("SELECT key_name,value_text FROM training_content",{}, {datasource:variables.datasource});for(var r in q)out[r.key_name]=r.value_text;return out;}
    struct function contentDefaults(){return{
        "site.name":"Training Ledger","site.tagline":"training curriculum by date","site.footer":"Every course logged, every signature accounted for.",
        "nav.weeks":"Courses","nav.roster":"Roster","nav.admin":"Edit Content","index.heading":"Training Courses by Date","index.new_week_btn":"+ New Course","index.empty_title":"No entries yet","index.empty_body":"Add or import your first dated training course.",
        "week.back_link":"All courses","week.edit_btn":"Edit Course","week.delete_btn":"Delete","week.topics_heading":"Topics & Lesson Plans","week.add_topic_btn":"+ Add Topic","week.attendance_heading":"Attendance","week.signoff_btn":"Open Sign-off Sheet",
        "session.heading":"Sessions","session.new_btn":"+ New Session","session.open_signoff_btn":"Open Sign-off Sheet","session.download_signoff_btn":"Download Sign-off Template","session.upload_signoff_btn":"Upload Signed Sheet",
        "people.heading":"Roster","people.add_btn":"+ Add Person","reports.heading":"Reports","reports.signoff_heading":"Signed Sign-off Sheets","reports.attendance_heading":"Attendance Matrix","account.heading":"Account","admin.heading":"Edit Content & Appearance"
    };}
    void function saveContent(required struct values){for(var k in arguments.values){if(k=="FIELDNAMES")continue;queryExecute("MERGE INTO training_content(key_name,value_text) KEY(key_name) VALUES(:k,:v)",{k:k,v:trim(arguments.values[k]&"")},{datasource:variables.datasource});}}
    void function resetContent(){queryExecute("DELETE FROM training_content",{}, {datasource:variables.datasource});}
    struct function theme(){var out=themeDefaults();var q=queryExecute("SELECT key_name,value_text FROM training_theme",{}, {datasource:variables.datasource});for(var r in q)out[r.key_name]=r.value_text;return out;}
    struct function themeDefaults(){return{"accent":"##2fd8a6","accent2":"##58d9ff","background":"##0a0d12","surface":"##111720","border":"##334155","text":"##eef2f6","muted":"##94a3b8"};}
    void function saveTheme(required struct values){for(var k in arguments.values){if(k=="FIELDNAMES"||!len(trim(arguments.values[k]&"")))continue;queryExecute("MERGE INTO training_theme(key_name,value_text) KEY(key_name) VALUES(:k,:v)",{k:k,v:trim(arguments.values[k]&"")},{datasource:variables.datasource});}}
    void function resetTheme(){queryExecute("DELETE FROM training_theme",{}, {datasource:variables.datasource});}

    // Prefer the key the driver reports for this insert; MAX(id) is only a last
    // resort because a concurrent insert can hand back another user's record.
    private numeric function insertedId(required struct result,required string tableName){if(structKeyExists(arguments.result,"generatedKey")&&isNumeric(arguments.result.generatedKey))return val(arguments.result.generatedKey);return newestId(arguments.tableName);}
    private numeric function newestId(required string tableName){if(!listFindNoCase("training_weeks,training_topics,training_videos,training_people,training_sessions",arguments.tableName))throw(type="Logicore.Training",message="Invalid table.");var q=queryExecute("SELECT MAX(id) id FROM "&arguments.tableName,{}, {datasource:variables.datasource});return val(q.id[1]);}
    private numeric function scalar(required string sql){var q=queryExecute(arguments.sql,{}, {datasource:variables.datasource});var c=listFirst(q.columnList);return val(q[c][1]);}
    private string function safeName(required string s){var x=reReplace(arguments.s,"[^A-Za-z0-9._ -]","_","all");return len(trim(x))?trim(x):"file";}
    private struct function row(required query q,required numeric n){var s={};for(var c in listToArray(q.columnList))s[lCase(c)]=q[c][n];return s;}
    private array function toArray(required query q){var a=[];for(var i=1;i<=q.recordCount;i++)arrayAppend(a,row(q,i));return a;}
}
