component output=false {
    property name="datasource";
    property name="outputPath";

    function init(required string datasource, required string outputPath) {
        variables.datasource = arguments.datasource;
        variables.outputPath = arguments.outputPath;
        variables.editableFields = ["ticket_no","model","serial","ra_no","tracking","carrier","address","status","ussi_resolution","addtl_info","origin_company","store_no","rack","bin"];
        variables.requiredFields = ["model","serial","carrier"];
        return this;
    }

    void function initSchema() {
        queryExecute("CREATE TABLE IF NOT EXISTS nc_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date_added DATE NOT NULL, ticket_no VARCHAR(255), model VARCHAR(255) NOT NULL, serial VARCHAR(255) NOT NULL, number VARCHAR(80) NOT NULL UNIQUE, ra_no VARCHAR(255), tracking VARCHAR(255), carrier VARCHAR(255) NOT NULL, address VARCHAR(1000), status VARCHAR(255), ussi_resolution VARCHAR(1000), addtl_info VARCHAR(2000), origin_company VARCHAR(255), store_no VARCHAR(255), rack VARCHAR(255), bin VARCHAR(255), filed_by_user_id BIGINT, filed_by_username VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)", {}, {datasource:variables.datasource});
        queryExecute("CREATE TABLE IF NOT EXISTS nc_number_counters (initials VARCHAR(12) NOT NULL, year_num INT NOT NULL, count_num INT NOT NULL DEFAULT 0, PRIMARY KEY(initials,year_num))", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_nc_number ON nc_items(number)", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_nc_serial ON nc_items(serial)", {}, {datasource:variables.datasource});
    }

    void function init() { initSchema(); }

    string function previewNextNumber(required string initials, numeric yearNum=year(now())) {
        var ini = uCase(trim(arguments.initials)); if (!len(ini)) ini="XX";
        var q=queryExecute("SELECT count_num FROM nc_number_counters WHERE initials=:i AND year_num=:y", {i:ini,y:arguments.yearNum}, {datasource:variables.datasource});
        var n=q.recordCount ? q.count_num[1]+1 : 1;
        return ini & right(arguments.yearNum,2) & "-" & n;
    }

    private string function generateNumber(required string initials, numeric yearNum=year(now())) {
        var ini=uCase(trim(arguments.initials)); if(!len(ini)) ini="XX";
        var n=0;
        transaction isolation="serializable" {
            var q=queryExecute("SELECT count_num FROM nc_number_counters WHERE initials=:i AND year_num=:y FOR UPDATE", {i:ini,y:arguments.yearNum}, {datasource:variables.datasource});
            n=q.recordCount ? q.count_num[1]+1 : 1;
            if(q.recordCount) queryExecute("UPDATE nc_number_counters SET count_num=:n WHERE initials=:i AND year_num=:y", {n:n,i:ini,y:arguments.yearNum}, {datasource:variables.datasource});
            else queryExecute("INSERT INTO nc_number_counters(initials,year_num,count_num) VALUES(:i,:y,:n)", {i:ini,y:arguments.yearNum,n:n}, {datasource:variables.datasource});
        }
        return ini & right(arguments.yearNum,2) & "-" & n;
    }

    struct function addItem(required struct fields, required struct user, required string initials) {
        validateRequired(arguments.fields);
        var number=generateNumber(arguments.initials,year(now()));
        var params={d:dateFormat(now(),"yyyy-mm-dd"),n:number,uid:arguments.user.id,un:arguments.user.username};
        var cols=[]; var binds=[];
        for(var f in variables.editableFields){ arrayAppend(cols,f); arrayAppend(binds,":"&f); params[f]=trim(arguments.fields[f] ?: ""); }
        queryExecute("INSERT INTO nc_items(date_added,number,filed_by_user_id,filed_by_username,"&arrayToList(cols)&") VALUES(:d,:n,:uid,:un,"&arrayToList(binds)&")",params,{datasource:variables.datasource});
        var q=queryExecute("SELECT * FROM nc_items WHERE number=:n",{n:number},{datasource:variables.datasource});
        return q.recordCount ? rowToStruct(q,1) : {};
    }

    struct function getItem(required numeric id) {
        var q=queryExecute("SELECT * FROM nc_items WHERE id=:id",{id:arguments.id},{datasource:variables.datasource});
        return q.recordCount ? rowToStruct(q,1) : {};
    }

    struct function updateItem(required numeric id, required struct fields) {
        var current=getItem(arguments.id); if(!structCount(current)) return {};
        var sets=[]; var params={id:arguments.id};
        for(var f in variables.editableFields){ if(structKeyExists(arguments.fields,f)){ arrayAppend(sets,f&"=:"&f); params[f]=trim(arguments.fields[f] ?: ""); } }
        if(!arrayLen(sets)) return current;
        var merged=duplicate(current); structAppend(merged,arguments.fields,true); validateRequired(merged);
        queryExecute("UPDATE nc_items SET "&arrayToList(sets)&", updated_at=CURRENT_TIMESTAMP WHERE id=:id",params,{datasource:variables.datasource});
        return getItem(arguments.id);
    }

    boolean function deleteItem(required numeric id) {
        var r={}; queryExecute("DELETE FROM nc_items WHERE id=:id",{id:arguments.id},{datasource:variables.datasource,result:"r"});
        return (r.recordCount ?: 0)>0;
    }

    struct function listItems(string search="",string status="",numeric limit=50,numeric offset=0) {
        var where=[]; var params={lim:{value:arguments.limit,cfsqltype:"cf_sql_integer"},off:{value:arguments.offset,cfsqltype:"cf_sql_integer"}};
        if(len(trim(arguments.search))){
            params.term="%"&trim(arguments.search)&"%";
            arrayAppend(where,"(number LIKE :term OR ticket_no LIKE :term OR model LIKE :term OR serial LIKE :term OR ra_no LIKE :term OR tracking LIKE :term OR carrier LIKE :term OR address LIKE :term OR status LIKE :term OR ussi_resolution LIKE :term OR addtl_info LIKE :term OR origin_company LIKE :term OR store_no LIKE :term OR rack LIKE :term OR bin LIKE :term OR filed_by_username LIKE :term)");
        }
        if(len(trim(arguments.status))){params.st=trim(arguments.status);arrayAppend(where,"status=:st");}
        var clause=arrayLen(where)?" WHERE "&arrayToList(where," AND "):"";
        var q=queryExecute("SELECT * FROM nc_items"&clause&" ORDER BY date_added DESC,id DESC LIMIT :lim OFFSET :off",params,{datasource:variables.datasource});
        var c=queryExecute("SELECT COUNT(*) c FROM nc_items"&clause,params,{datasource:variables.datasource});
        var statuses=queryExecute("SELECT DISTINCT status FROM nc_items WHERE status IS NOT NULL AND status<>'' ORDER BY status",{}, {datasource:variables.datasource});
        var st=[]; for(var item in statuses) arrayAppend(st,item.status);
        return {items:queryToArray(q),total:c.c[1],statuses:st};
    }

    string function buildExport(required array rows) {
        var filename="SMS_NonConforming_"&dateFormat(now(),"yyyymmdd")&"_"&timeFormat(now(),"HHmmss")&".xlsx";
        var path=variables.outputPath&filename;
        var sheet=spreadsheetNew("NonConforming",true);
        var headers=["Date Added","Number","Ticket ##","Model ##","Serial ##","RA ##","Tracking","Carrier","Address","Status","USSI Resolution Confirmation","Addtl Info","Origin Company","Store ##","Rack","Bin","Filed By"];
        spreadsheetAddRow(sheet,arrayToList(headers));
        for(var item in arguments.rows) spreadsheetAddRow(sheet,arrayToList([item.date_added?:"",item.number?:"",item.ticket_no?:"",item.model?:"",item.serial?:"",item.ra_no?:"",item.tracking?:"",item.carrier?:"",item.address?:"",item.status?:"",item.ussi_resolution?:"",item.addtl_info?:"",item.origin_company?:"",item.store_no?:"",item.rack?:"",item.bin?:"",item.filed_by_username?:""]));
        spreadsheetFormatRow(sheet,{bold:true,fgcolor:"2F3B4C",fontcolor:"FFFFFF"},1);
        spreadsheetWrite(sheet,path,true);
        return filename;
    }

    string function buildZpl(required struct item) {
        var number=trim(arguments.item.number ?: "");
        var labelW=609; var labelH=812; var margin=20; var qrSize=170; var qrGap=20;
        var usable=labelW-(2*margin); var n=max(len(number),1); var h=int(min(labelH-(2*margin)-qrSize-qrGap,max(40,usable/(n*0.65))));
        var area=labelH-(2*margin)-qrSize-qrGap; var yNum=margin+int((area-h)/2); var yQr=labelH-margin-qrSize; var xQr=int((labelW-qrSize)/2);
        return "^XA"&chr(10)&"^PW"&labelW&chr(10)&"^LL"&labelH&chr(10)&"^CF0,"&h&chr(10)&"^FO0,"&yNum&"^FB"&labelW&",1,0,C,0^FD"&number&"^FS"&chr(10)&"^FO"&xQr&","&yQr&chr(10)&"^BQN,2,6"&chr(10)&"^FDLA,"&number&"^FS"&chr(10)&"^XZ";
    }

    private void function validateRequired(required struct fields){ var missing=[]; for(var f in variables.requiredFields) if(!len(trim(arguments.fields[f] ?: ""))) arrayAppend(missing,f); if(arrayLen(missing)) throw(type="Logicore.Validation",message="Missing required field(s): "&arrayToList(missing,", ")); }
    private struct function rowToStruct(required query q, required numeric n){var s={};for(var c in listToArray(q.columnList))s[lCase(c)]=q[c][n];return s;}
    private array function queryToArray(required query q){var a=[];for(var i=1;i<=q.recordCount;i++)arrayAppend(a,rowToStruct(q,i));return a;}
}
