component output=false {
    binary function build(required struct trainingSession,required array attendees){
        var lines=[];var t=arguments.trainingSession;
        arrayAppend(lines,{text:"Training Sign-off Sheet",size:20,y:744});
        arrayAppend(lines,{text:(len(t.week_start_date?:"")?dateFormat(t.week_start_date,"mmmm d, yyyy"):"Training date")&": "&t.week_title,size:11,y:718});
        arrayAppend(lines,{text:"Trainer: "&t.trainer_name&"    Date: "&(t.session_date?:"")&"    Location: "&(t.location?:""),size:10,y:700});
        arrayAppend(lines,{text:"Attendee                                  Signature                                  Date",size:10,y:670});
        var y=648;if(!arrayLen(arguments.attendees)){arrayAppend(lines,{text:"No attendees are currently marked present.",size:10,y:y});}
        for(var person in arguments.attendees){arrayAppend(lines,{text:person.name&"    ______________________________    ____________",size:10,y:y});y-=24;if(y<55)break;}
        arrayAppend(lines,{text:"Generated by USSI Nexus - Training Tracker",size:8,y:34});
        var stream="";for(var line in lines)stream&="BT /F1 "&line.size&" Tf 48 "&line.y&" Td ("&pdfText(line.text)&") Tj ET"&chr(10);
        var objects=[
            "<< /Type /Catalog /Pages 2 0 R >>",
            "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
            "<< /Length "&len(stream)&" >>"&chr(10)&"stream"&chr(10)&stream&"endstream",
            "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        ];
        var pdf="%PDF-1.4"&chr(10);var offsets=[];
        for(var i=1;i<=arrayLen(objects);i++){arrayAppend(offsets,len(pdf));pdf&=i&" 0 obj"&chr(10)&objects[i]&chr(10)&"endobj"&chr(10);}
        var xref=len(pdf);pdf&="xref"&chr(10)&"0 "&(arrayLen(objects)+1)&chr(10)&"0000000000 65535 f "&chr(13)&chr(10);
        for(var offset in offsets)pdf&=numberFormat(offset,"0000000000")&" 00000 n "&chr(13)&chr(10);
        pdf&="trailer"&chr(10)&"<< /Size "&(arrayLen(objects)+1)&" /Root 1 0 R >>"&chr(10)&"startxref"&chr(10)&xref&chr(10)&"%%EOF"&chr(10);
        return charsetDecode(pdf,"utf-8");
    }
    private string function pdfText(any value=""){var s=reReplace(value&"","[^ -~]","?","all");s=replace(s,"\\","\\\\","all");s=replace(s,"(","\\(","all");return replace(s,")","\\)","all");}
}
